Config cache fpga
openhwgroup/cva6 pull request #1000
Opened 2022-11-24 10:38 UTC by sjthales

* Configuration of the number of ways of data and instruction caches for the FPGA version of the CV32A6.

* Fix readme

2022-11-24 10:41 UTC, zarubaf approved these changes
👍

2022-11-24 15:15 UTC, jquevremont commented
Sorry @zarubaf, I wrongly hit re-request review.

2022-11-25 07:18 UTC, JeanRochCoulon requested changes
Hello @sjthales, this is a good PR. Happy to know that the cache works with 2 ways. I am thinking about modifying the cache paramaters of our configurations, cv32a60x. Have a good day.

2022-11-25 07:18 UTC, JeanRochCoulon commented on core/include/ariane_pkg.sv
> +    localparam int unsigned CONFIG_L1I_SIZE    = cva6_config_pkg::CVA6ConfigIcacheSetAssoc * 4096; // one icache way is 4 KBytes  // 16*1024;
Could you remove the "// 16*1024" unuseful comment

2022-11-25 07:18 UTC, JeanRochCoulon commented on core/include/ariane_pkg.sv
> +    localparam int unsigned ICACHE_SET_ASSOC   = cva6_config_pkg::CVA6ConfigIcacheSetAssoc; // number of ways // 4; // Must be between 4 to 64
Could you remove the "// 4" comment
The other comment suggests that it must be between 4 to 64, and you set up it to 2 ?!? I suppose you can, in that case remove the suggestion.

2022-11-25 07:18 UTC, JeanRochCoulon commented on core/include/ariane_pkg.sv
> +    localparam int unsigned CONFIG_L1D_SIZE    = cva6_config_pkg::CVA6ConfigDcacheSetAssoc * 4096; // one icache way is 4 KBytes  //32*1024;
idem on comments

2022-11-25 07:18 UTC, JeanRochCoulon commented on core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
> +// Original Author: Sébastien Jacq
You are not the original author of this file, please fix it

2022-11-25 08:18 UTC, sjthales commented
requested modifications done

2022-11-25 12:52 UTC, JeanRochCoulon approved these changes
Thanks @sjthales for these modifications and this contribution. I will merge it asap.

2022-11-25 12:56 UTC, merged