Add Ara support
openhwgroup/cva6 pull request #1024
Opened 2022-12-23 19:19 UTC by niwis

Support Ara via a custom, parametrised accelerator interface.
- `cv64a6_imafdcv_sv39_config_pkg.sv` enables V extension
- Pre-processor constant `ARIANE_ACCELERATOR_PORT` enables the interface between CVA6 and Ara. This may be merged into X-interface at some point.
- FPU is bumped to a SIMD-compatible version

Backwards compatibility should be preserved. Once this is merged, we will change the reference of Ara upstream CVA6.

Merry Christmas!

2023-01-10 17:10 UTC, MikeOpenHWGroup commented
Thanks a _lot_ for this @niwis.  I am just seeing this now - it got lost in the noise of my travels to the RISC-V Summit and the holidays.

Question for @JeanRochCoulon - should this pull-request be targeted to the `dev` branch?

2023-01-10 17:17 UTC, JeanRochCoulon commented
Great PR @niwis thank you very much.
Adding to the master branch is maybe too early due to the fact that the interface is not yet CV-X-IF. @mike, your idea to host this in a new dev branch is smart.
In the next week, @ASintzoff and me will be available to review the PR.
à bientôt !!

2023-01-16 15:01 UTC, JeanRochCoulon commented
Hello @niwis 
The PR includes a lot of modifications. And the PR is not finished. That's why I have created a new cva6 branch called dev/ara_integration. Can you submit a PR to this new branch ?
See you

2023-01-18 19:00 UTC, niwis commented
Thanks @JeanRochCoulon and @MikeOpenHWGroup! A few follow-ups from my side regarding this:
- Regarding CVXIF compatibility: This is a major modification and I am not aware of a timeline for this. This is why we discussed with mike (correct me if I misunderstood) to initially add the Ara *accelerator interface* next to CVXIF and then merge both in a second, independent step.
- The accelerator interface is fully parametrised. So, without defining `ARIANE_ACCELERATOR_PORT`, there would be no change to the current state or interfaces of CVA6.
- Merging this into a stale branch would not help with keeping the modifications in sync with upstream development. Moreover, we would lose flexibility in our development.

Let me know what you think. I would also be happy to discuss this further next week.
Best, Nils

2023-01-28 09:32 UTC, jennycoder-fly commented
@niwis Hi, How can I use Ara in openpiton+ariane system？

2023-02-21 18:40 UTC, zarubaf requested changes
Thanks so much for this initial contribution. I've given this a first pass and reviewed particular with respect to separating concerns between CVA6 base and the Ara contribution, so that we have a path forward to merge this. 

Please, everybody, feel free to comment.

2023-02-21 18:40 UTC, zarubaf commented on core/commit_stage.sv
> +    input  logic                                    flush_dcache_i,       // request to flush dcache -> also flush the pipeline
Can you move everything from here to a separate commit module? `commit_stage_rvv` or something like this. That makes the change easier and separated. You can wire the `dirty_fp_state_o` on the modules port in the top.

2023-02-21 18:40 UTC, zarubaf commented on core/controller.sv
> +    input  logic            acc_store_pending_i,    // Store instruction pending on an accelerator
Can we move the entire change to the same (new) module above and only provide an input `ait_acc_store_i` which we use as `wait_acc_store_q` in the `halt_o`?

2023-02-21 18:40 UTC, zarubaf commented on core/csr_regfile.sv
> +                    end
@JeanRochCoulon  That's good and equivalent to the original code. It needs to be off.

2023-02-21 18:40 UTC, zarubaf commented on core/csr_regfile.sv
> +                riscv::CSR_ACC_CONS:           if (ENABLE_ACCELERATOR) acc_cons_d  = {{riscv::XLEN-1{1'b0}}, csr_wdata[0]}; // enable bit
This needs to be fully gated by an `ifdef` right? Otherwise, the CSR will still be present and not throw an illegal instruction exception.

2023-02-21 18:40 UTC, zarubaf commented on core/issue_read_operands.sv
>      output logic [31:0]                            cvxif_off_instr_o,
Can we move most of the logic to a module outside? I have the feeling just `stall` is needed. We can have a `acc_stall_i`, `acc_ready_i`. This would make the change to the module less intrusive.

2023-02-21 18:40 UTC, zarubaf commented on core/load_unit.sv
> +    input  logic                     stall_ld_i,
Well the same for all the other stall signals :-)

2023-02-21 18:40 UTC, zarubaf commented on core/serdiv.sv
> +          in_rdy_o  = (STABLE_HANDSHAKE) ? 1'b1 : 1'b0;
Could we make this default for both? Or is it locking up CVA6. Not sure I fully understand the comment.

2023-02-22 01:20 UTC, jennycoder-fly commented on core/decoder.sv
> +        end
Thanks so much

2023-02-22 05:36 UTC, JeanRochCoulon requested changes

2023-02-22 05:36 UTC, JeanRochCoulon commented on core/axi_shim.sv
> +  assign axi_req_o.ar.cache  = 4'b0010;
As reported in #948 , the CVA6 AXI does not support the MODIFIABLE transaction

2023-02-22 05:36 UTC, JeanRochCoulon commented on core/cva6.sv
> +`ifdef ARIANE_ACCELERATOR_PORT
When possible, do not use ifdef commands. Take example on cvxif to avoid this command

2023-02-22 05:36 UTC, JeanRochCoulon commented on core/serdiv.sv
> +          in_rdy_o  = (STABLE_HANDSHAKE) ? 1'b1 : 1'b0;
serdiv is instantiated in mult module which does not set the STABLE_HANDSHAKE parameter. Can we remove the modification ?

2023-02-28 19:45 UTC, niwis commented
Thank you, @zarubaf and @JeanRochCoulon, for your initial review! As discussed in today's technical meeting, we await a decision on whether you want to merge this feature with the currently implemented accelerator port (next to CVXIF). If so, we will be happy to
- implement your feedback,
- rebase onto the latest version of the master branch (new conflicts have emerged since this PR was opened),
- and to ensure the current scalar regression tests (Github + Thales Gitlab) and Ara's CI pass.

Looking forward to hearing back!

2023-03-07 13:51 UTC, niwis commented
As suggested, some previous modifications of this PR have been moved to #1101, #1102, #1103, #1104, and #1105. Once they are merged, we can rebase this PR and continue with the steps above https://github.com/openhwgroup/cva6/pull/1024#issuecomment-1448762948. Let us know if more changes in this PR should be treated separately.

Cheers,
Nils

2023-03-07 13:55 UTC, zarubaf commented
Thanks @niwis, much appreciated!

2023-03-07 14:20 UTC, niwis commented on core/ariane.sv
> +  parameter type axi_rsp_t = ariane_axi::resp_t
Continued in #948

2023-03-07 14:21 UTC, niwis commented on core/include/ariane_pkg.sv
> +    localparam int unsigned DCACHE_USER_LINE_WIDTH  = (AXI_USER_WIDTH == 1) ? 4 : cva6_config_pkg::CVA6ConfigDcacheLineWidth; // in bit
Continued in #1104

2023-03-07 14:22 UTC, niwis commented on vendor/pulp-platform_fpnew.vendor.hjson
> +        rev: "vec",
Continued in #1102

2023-03-07 14:36 UTC, JeanRochCoulon commented
Very good @niwis. At 9pm, at the time we usually eat (or drink), the CI will run on all your PRs. Let's see the result on Tomorrow.

2023-03-07 14:41 UTC, niwis commented
Let's see tomorrow, then. Bon appétit ! :-)

2023-04-16 18:09 UTC, zarubaf commented
I think we should have all dependencies of this one in @niwis - can we do a final rebase so that we are clean with the diff?

Then we'll review again and hopefully be all a happy CVA6 family :-D

2023-04-28 08:04 UTC, domenicw commented
Thanks for all of this work, this looks really great. Regarding our (@zarubaf, @michael-platzer, and me) proposal for the multiple accelerator interface problem, I see only minimal changes that need to happen in this PR.

**First**, as @zarubaf has already mentioned in his review, the `acc_dispatcher` module should be moved out of the `ex_stage` and into the top module (`cva6`). All special signals that would be needed from the `ex_stage` (which there seem to none at the moment) should rather be routed out of it and into the new top level `acc_dispatcher`.

**Second**, there should only be a single `cva6` extension interface. With this PR the accelerator interface is added to the ports of the top module. These should be removed again and instead the `cvxif_req_o` and `cvxif_resp_i` ports should be used. For that, the top module parameter list would need to gain two new parameters:

```SystemVerilog
parameter type cvxif_req_t  = cvxif_pkg::cvxif_req_t,
parameter type cvxif_resp_t = cvxif_pkg::cvxif_resp_t
```

And then in the ports list:

```SystemVerilog
output cvxif_req_t  cvxif_req_o,
input  cvxif_resp_t cvxif_resp_i
```

This way the default would still be the x-interface, but Ara could just replace the parameters and use its own signal types. This should not lead to any problems in this PR, since only the x-interface or the accelerator interface can be enabled at a time. Though we need to make sure that the `cvxif_req_o` signals are tied to zero if neither of the two interface are enabled.
The `cvxif_req_o` and `cvxif_resp_i` signals would then be directly routed to the `acc_dispatcher` module.

---

These changes should be enough for this PR. In a next step, the x-interface should be adapted to use this new accelerator interface regime. Meaning it should gain its own `cva6_accel_first_pass_decoder` module with everything currently residing in the decoder. Further, all of the x-interface logic currently in the `ex_stage` would move into a `acc_dispatcher` module. All other logic distributed in the different stages could then be merged with the `accelerator` logic of this PR. There is no need for these redundant signals, since all accelerator offloading interfaces mostly do the same things.

The `cva6` project is heavily pushing the x-interface. Therefore we propose that the default for the accelerator interface becomes the x-interface. Meaning the `cva6_accel_first_pass_decoder` and the `acc_dispatcher` implementations that live in this project will be the ones for the x-interface. If you want to use your custom interface (e.g. Ara accelerator interface), then these custom modules would live in your personal project. Bender could then gain a new target, which can be used to exclude the default accelerator interface of `cva6`. Something like:

```yaml
- target: not(exclude_default_xif)
  files:
    - core/cva6_accel_first_pass_decoder.sv
    - core/acc_dispatcher.sv
```

---

All of these changes should make it easier to do a custom accelerator interface implementation. The upstream `cva6` project would not needed to be touched in any way and no new ports would need to be added to the top level module. The only time the upstream repo would need to be touched is if new signals need to be routed into or out of the `acc_dispatcher`. But as we mentioned during our proposal, the port list these modules would be unstable. If a new port is added, it has to be correctly implemented for the x-interface (the upstream always has to work). But for everyone else with their custom implementation, updating to a newer `cva6` version might mean to also update their custom modules.

@niwis, @JeanRochCoulon, and everyone else, let me know what you think of these changes and if anything is unclear. If further explanation is needed, we could also do another face to face meeting.

---

Also, just as a small detail, we might want to revisit the naming of these two modules, the pre-decoder and the dispatcher. Just to make them more consistent.

2023-06-16 09:36 UTC, zarubaf commented
@niwis do you maybe have an ETA for us on those changes? Would be super cool if we can get this is in 😄

2023-06-16 09:41 UTC, niwis commented
I'll try to tackle this this weekend. Another rebase is done and Ara's CI is passing, so the only thing missing is implementing the feedback

2023-06-20 18:38 UTC, niwis commented on core/commit_stage.sv
> +    input  logic                                    flush_dcache_i,       // request to flush dcache -> also flush the pipeline
done, moved to `acc_dispatcher`.

2023-06-20 18:39 UTC, niwis commented on core/controller.sv
> +    input  logic            acc_store_pending_i,    // Store instruction pending on an accelerator
done, moved to `acc_dispatcher` and wired `halt` from there.

2023-06-20 18:42 UTC, niwis commented on core/csr_regfile.sv
> +                riscv::CSR_ACC_CONS:           if (ENABLE_ACCELERATOR) acc_cons_d  = {{riscv::XLEN-1{1'b0}}, csr_wdata[0]}; // enable bit
Right. I solved this by setting `update_access_exception=1'b` (the default behaviour) when this is disabled (https://github.com/openhwgroup/cva6/blob/646f33caee03a4e5a5f781b935a42fe9e7d959b2/core/csr_regfile.sv#LL829C29-L829C29). This avoids using `ifdef`s

2023-06-20 18:43 UTC, niwis commented on core/csr_regfile.sv
> +
done

2023-06-20 18:43 UTC, niwis commented on core/ex_stage.sv
> +        .stall_st_i            ( 1'b0 ),
That's indeed an artefact. I have removed it.

2023-06-20 18:43 UTC, niwis commented on core/ex_stage.sv
> +    end: gen_no_accelerator
done

2023-06-20 18:44 UTC, niwis commented on core/include/axi_intf.sv
> +`ifndef SPYGLASS
This is indeed not needed. I have dropped the change.

2023-06-20 18:45 UTC, niwis commented on core/issue_read_operands.sv
>      output logic [31:0]                            cvxif_off_instr_o,
Done. moved to `acc_dispatcher` for now.

2023-06-20 18:45 UTC, niwis commented on core/load_store_unit.sv
> +
yes, dropped this diff

2023-06-20 18:46 UTC, niwis commented on core/issue_stage.sv
> +    input  logic                                     acc_cons_en_i,
done. moved to `acc_dispatcher`

2023-06-20 18:46 UTC, niwis commented on core/load_unit.sv
> +    input  logic                     stall_ld_i,
manual constant propagation :D

2023-06-20 18:49 UTC, niwis commented on core/serdiv.sv
> +          in_rdy_o  = (STABLE_HANDSHAKE) ? 1'b1 : 1'b0;
I don't think so. this is needed by Ara: https://github.com/pulp-platform/ara/blob/ee887bdb20ce396d438639a85bc2640718806fdc/hardware/src/lane/simd_div.sv#L313
perhaps @mp-17 can comment further

2023-06-20 18:53 UTC, niwis commented on core/decoder.sv
> +        end
I moved as much as possible to `cva6_accel_first_pass_decoder`. I did not see a cleaner way to mux than in the updated proposal without changing half of the file (basically every direct assignment into the output struct). Other suggestions are welcome!

2023-06-20 18:55 UTC, niwis commented on core/include/ariane_pkg.sv
> +    // Is the accelerator enabled?
The problem is that we (still) need a precompiler constant for the ifdef in the port list. But perhaps we can remove it.

2023-06-20 18:55 UTC, niwis commented on core/include/ariane_pkg.sv
> +    localparam bit XF16    = cva6_config_pkg::CVA6ConfigF16En | RVV; // Is half-precision float extension (Xf16) enabled
@mp-17 can you comment on this?

2023-06-20 18:56 UTC, niwis commented on core/include/ariane_pkg.sv
> +
done, `core/include/acc_pkg.sv`.

2023-06-20 19:10 UTC, niwis commented
Thank you @zarubaf @JeanRochCoulon @domenicw for your thorough review! I hope I was able to address most feedback. In particular:
1. Most new logic was moved into the new modules, foremost `acc_dispatcher`. This one is a bit bloated now, we can easily split it up or rename it if preferred.
2. The accelerator interface was removed and instead the cvxif is overloaded as suggested by @domenicw.

With 2., the `ifdef` is now only needed to add the invalidation interface. From my point of view, this interface could also be added unconditionally, which, however, would again change the interfaces. I will let the maintainers decide :-)

Let me know if there are further comments or suggestions!

2023-06-21 18:46 UTC, zarubaf commented on core/cva6.sv
> +  end
Very nice!

2023-06-21 18:48 UTC, zarubaf commented on core/include/ariane_pkg.sv
> +    // Is the accelerator enabled?
I think if we can fold it into the structs, we can get rid of it completely.

2023-06-21 18:49 UTC, zarubaf commented on corev_apu/src/ariane.sv
> +`endif
Maybe it is time to deprecate this one? Can you use the `cva6` top for your use-case? Then we don't really need to change anything here, agree?

2023-06-21 18:51 UTC, zarubaf commented
@niwis I am super, super happy with how this turned out. The implementation is really clean now. The last remaining thing is the invalidation interface, which IMHO we can fold into the structs as well. If I am mistaken I'd be still okay to go ahead and merge this. Thanks a lot for all the work you put into this!

@JeanRochCoulon can you help us with a bit more information on the failing Thales CI? I am sure it is only some setup thing.

2023-06-21 20:41 UTC, niwis commented on corev_apu/src/ariane.sv
> +`endif
Absolutely!

2023-06-21 20:52 UTC, niwis commented on core/cva6.sv
> +  output logic                         inval_ready_o,
The only reason why they are separate now is that (at least in Ara's system) they don't interface with the accelerator (ara) itself but with the `axi_inval_filter`, which issues invalidation requests based on aw transactions and is located outside of Ara. It would be possible to split/pack the struct in the system, but that might be a bit misleading and confusing. Otherwise, we could also change this into a parametric `coherence_[req|resp]` struct that could be used for arbitrary coherence signals in the future. Those are just a few ideas, happy to implement the preferred option :-)

2023-06-22 06:16 UTC, JeanRochCoulon commented
Sure, I will !

2023-06-23 08:47 UTC, zarubaf commented on core/cva6.sv
> +  output logic                         inval_ready_o,
I definitely get the point, I think this needs a bit more thinking though and to not block this PR I'd prefer to keep it in the `cvxif_req_t` / `cvxif_resp_t` struct for the moment, then we do not add new ports that we potentially can't remove anymore. Does that make sense?

2023-06-23 11:53 UTC, mp-17 commented on core/include/ariane_pkg.sv
> +    localparam bit XF16    = cva6_config_pkg::CVA6ConfigF16En | RVV; // Is half-precision float extension (Xf16) enabled
Hello @JeanRochCoulon, 

From the specs: 
> Vector floating-point instructions require the presence of base scalar floating-point extensions corresponding to the supported vector floating-point element widths.

And, again, for the `V` extension in particular:
> The V extension requires the scalar processor implements the F and D extensions

So, we cannot completely disable CVA6's FPU if Ara is enabled.

They dropped the mandatory support for 16-bit floating-point in the last version of the specs, so we should modify this parameter assignment. Nevertheless, `XF16` should be asserted if Ara is deployed with `XF16` support.

2023-06-23 12:16 UTC, mp-17 commented on core/serdiv.sv
> +          in_rdy_o  = (STABLE_HANDSHAKE) ? 1'b1 : 1'b0;
Yes, I modified it for Ara to keep the `in_rdy_o` asserted during the handshake and this is needed.
@zarubaf I think the stable handshake was creating a problem with CVA6 back then; I am not sure anymore. I launched a CI here with CVA6 using the stable handshake: https://github.com/pulp-platform/ara/actions/runs/5356243109

2023-06-23 14:20 UTC, niwis commented on core/cva6.sv
> +  output logic                         inval_ready_o,
Makes sense! Done.

2023-06-23 14:21 UTC, niwis commented on core/cva6.sv
> +`ifdef ARIANE_ACCELERATOR_PORT
Done. The ifdef has been completely removed.

2023-06-23 14:21 UTC, niwis commented on core/include/ariane_pkg.sv
> +    // Is the accelerator enabled?
Done

2023-06-25 21:00 UTC, JeanRochCoulon commented on core/include/ariane_pkg.sv
> +    localparam bit XF16    = cva6_config_pkg::CVA6ConfigF16En | RVV; // Is half-precision float extension (Xf16) enabled
From your explanation, I understand that ARA uses F and D extensions implemented inside CVA6. Understood.

2023-06-27 08:35 UTC, JeanRochCoulon commented
Hello @niwis 
We started to review the code. Nice improvements ! Congratulations. 
When enabling the RVV, we faced a lack of files
Moreover, the overloaded cvxif package is not in GitHub PR

%Error: /home/jrcoulon/Projects/ara/core-v-verif/core-v-cores/cva6/core/decoder.sv:82:9: Cannot find file containing module: 'cva6_accel_first_pass_decoder'
   82 |         cva6_accel_first_pass_decoder i_accel_decoder (
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cheers

2023-06-27 09:38 UTC, niwis commented
Thank you @JeanRochCoulon for your review.

Regarding the missing file:
The accelerator first pass decoder is meant to be provided by the accelerator since it is specific to the accelerator/extension. For that reason, Ara's first pass decoder is located in the [Ara repo](https://github.com/pulp-platform/ara/blob/main/hardware/src/cva6_accel_first_pass_decoder.sv). I have added a stub to make the tools happy during elaboration. However, it should never be instantiated (the instantiation is guarded by `ENABLE_ACCELERATOR`). Let's see if this fixes the Thales CI.

Regarding the overloaded cvxif:
This PR parametrises the cvxif port type. The type needs to be overloaded when CVA6 is instantiated in a system that uses a different accelerator interface ([`ara_system`](https://github.com/pulp-platform/ara/blob/eeb5d5d4f31f5a3839d2c55ab87169164aec0e0b/hardware/src/ara_system.sv#L116-L117) in our case). What exactly is missing in this PR?
https://github.com/openhwgroup/cva6/blob/82e928952f2e416a7d9722a005ccad2311e01635/core/cva6.sv#L44-L45

2023-06-29 05:57 UTC, JeanRochCoulon commented
@niwis The Thales CI was down from 2/3 days due to https://github.com/openhwgroup/cva6/pull/1273 PR. I reverted this PR to make VCS pass. Of course, the drawback on VCS should be investigated to fix Questa.
With this revert, the ARA CI should be better. Could you rebase this PR with master to include the revert to launch the CI please ?
Have a nice day !

2023-06-29 08:29 UTC, niwis commented
Rebase is done @JeanRochCoulon

2023-06-30 04:56 UTC, JeanRochCoulon commented
Hello @niwis 
accelerate_req_t and accelerate_resp_t are defined twice in the code: in acc_pkg and in ariane_pkg, I wonder whether it is ok ?

BTW, the UVM simulation is not working, I am investigating

2023-06-30 08:08 UTC, niwis commented
Thanks, @JeanRochCoulon, for catching this. I have removed the old `accelerator_[req|resp]_t` definition in `ariane_pkg`. There may have been a type mismatch in `acc_dispatcher`, which should also be fixed now.

2023-07-03 16:02 UTC, JeanRochCoulon commented
@niwis @zarubaf  The CSR compliance test are failed on master, so ARA is not guilty   :-)

On synthesis side, I will have a look

2023-07-03 16:03 UTC, zarubaf commented
> @niwis @zarubaf The CSR compliance test are failed on master, so ARA is not guilty :-)
> 
> On synthesis side, I will have a look

2023-07-03 16:03 UTC, zarubaf commented
> @niwis @zarubaf The CSR compliance test are failed on master, so ARA is not guilty :-)
> 
> On synthesis side, I will have a look

2023-07-03 16:04 UTC, zarubaf commented
> @niwis @zarubaf The CSR compliance test are failed on master, so ARA is not guilty :-)
> 
> On synthesis side, I will have a look

I just wanted to say thank you and clicked everywhere - oops! 😅

2023-07-04 09:41 UTC, JeanRochCoulon commented
For information, I posted a PR to pass the synthesis:
https://github.com/pulp-platform/cva6/pull/30

This should help.

2023-07-04 10:38 UTC, niwis commented
Thanks a lot, @JeanRochCoulon! It is merged.

2023-07-05 11:11 UTC, zarubaf commented
As far as I understood we are waiting for CI to re-trigger. Yesterday's CI was failing because of a full disk, which has been changed. Let's cross fingers for tonight :-D

2023-07-05 12:55 UTC, JeanRochCoulon commented
We have fixed CI Today (I hope, to be confirmed this evening).

@niwis  A conflict must be resolved... What is the plan?  
1. To pass the CI before solving the conflict, wait for the CI fixed then solve the conflict or 
2. To solve it before this evening ?

2023-07-06 08:18 UTC, niwis commented
It looks like the CI didn't trigger last night. @JeanRochCoulon I can rebase and resolve the conflicts, but it might introduce new regressions. Or we can try to get this version to pass first. As you prefer.

2023-07-06 08:24 UTC, JeanRochCoulon commented
Ok, we can first pass the CI before rebasing.

PS: Thales CI is down, I try to fix it up Today

2023-07-06 21:47 UTC, JeanRochCoulon commented
Good news, the Thales CI is green (all fails are understood and not related to ARA), you can rebase.

2023-07-10 15:12 UTC, merged