Bootrom.sv : force the use of python2
openhwgroup/cva6 pull request #1097
Opened 2023-03-06 16:21 UTC by eyssartk

The makefile target to generate the bootrom system verilog assumes a python2 binary behind the python environment call. Python2 is not the default anymore on many systems.
This solves issue #1086.

2023-03-06 17:31 UTC, zarubaf commented
Honestly, I would prefer if we could update the code to `Python 3` instead of `Python 2`. `Python 2` is dead (luckily).

2023-03-06 17:44 UTC, eyssartk commented
I agree. I tried to look at it, but the hexlify was not easy to handle. I might try again.

2023-03-07 11:44 UTC, eyssartk commented
Ready to merge on my side

2023-03-07 11:46 UTC, zarubaf approved these changes
Cool, thanks!

2023-03-07 13:14 UTC, JeanRochCoulon commented
@Gchauvon This podification should not impact the bootrom output, could you double check this point ?    I prefer to verify it before merging.

2023-03-07 13:20 UTC, ASintzoff requested changes
Few Python cleanup

2023-03-07 13:20 UTC, ASintzoff commented on corev_apu/bootrom/gen_rom.py
> +def parse() :
Useless space before `:`

`def parse() :` => `def parse():`

2023-03-07 13:20 UTC, ASintzoff commented on corev_apu/bootrom/gen_rom.py
> +    file = args.filename[0];
Useless `;`

2023-03-07 13:20 UTC, ASintzoff commented on corev_apu/bootrom/gen_rom.py
>      align = (int((len(rom) + 7) / 8 )) * 8;
Useless `;`

2023-03-07 14:20 UTC, Gchauvon commented
LGTM

2023-03-07 14:39 UTC, eyssartk commented
Pylint is 7.4, I will stop here :)

2023-03-07 17:30 UTC, merged