For 64bit Performance counters
openhwgroup/cva6 pull request #1129
Opened 2023-03-21 14:48 UTC by TulikaSi

Implementation of **optional six 64 bit** Generic Counters, **mhpmcounter3–mhpmcounter8** along with their 32 bit counterparts **mhpmcounter3h–mhpmcounter8h**.
The event selector CSRs **mhpmevent3–mhpmevent8** have also been implemented in compliance with RISC V specifications and CVA6 requirements.

2023-03-21 22:22 UTC, JeanRochCoulon commented
Thales CI is failed. Can you rebase your PR? I think it will help.

2023-03-22 07:49 UTC, JeanRochCoulon commented
@jquevremont @sjthales @ASintzoff 

Congratulations @TulikaSi , the Thales CI is green !!!

We can start the code review. One question: Is the RTL aligned with CSR specification hosted in CVA6 repository ?

2023-03-22 10:12 UTC, ASintzoff requested changes

2023-03-22 10:12 UTC, ASintzoff commented on core/perf_counters.sv
Could you factorize the code to avoid repetitions?

Code in each `case(mhpmevent_q[i])` appears to be the same.

2023-03-23 00:34 UTC, Jbalkind commented
Could we get some documentation of what this PR is doing? Why does it rename the performance counters that were there already but not change their implementation? It would be particularly helpful to keep the useful names as comments if the function of the performance counters themselves has not changed.

2023-03-23 08:42 UTC, TulikaSi commented
> @jquevremont @sjthales @ASintzoff
> 
> Congratulations @TulikaSi , the Thales CI is green !!!
> 
> We can start the code review. One question: Is the RTL aligned with CSR specification hosted in CVA6 repository ?

Yes @JeanRochCoulon I have tried to incorporate all the specifications wrt performance counters in the requirement specifications

2023-03-23 13:02 UTC, jquevremont commented
For information:
The specification is here: https://github.com/openhwgroup/cva6/blob/master/docs/02_cva6_requirements/cva6_requirements_specification.rst#performance-counters

2023-03-27 06:21 UTC, TulikaSi commented on core/perf_counters.sv
Hi @ASintzoff I have done the changes in the latest commit.

2023-03-27 09:16 UTC, JeanRochCoulon commented
@jquevremont and @sjthales
As you leaded requirements on perf counters, can you check that the implementation done by Tulika is aligned with your expectation?  Alignment with CSR specification, functionalities, register names, enable/disable, ... etc
As soon as it is ok for you @ASintzoff and me will start reviewing the code.

2023-04-03 16:24 UTC, jquevremont commented
> @jquevremont and @sjthales As you leaded requirements on perf counters, can you check that the implementation done by Tulika is aligned with your expectation? Alignment with CSR specification, functionalities, register names, enable/disable, ... etc As soon as it is ok for you @ASintzoff and me will start reviewing the code.

See separate email.

2023-04-04 09:05 UTC, jquevremont commented on core/include/riscv_pkg.sv
This has not been updated in line with the other modifications.

2023-04-04 10:20 UTC, jquevremont requested changes
Shadow performance counters need to be implemented/updated (``hpmcounter``, starting at CSR address 0xC03) according to ``mhpmcounter`` modifications.
``mcountinhibit`` needs to be implemented too, but it's not blocking and can be deffered.

2023-04-04 10:20 UTC, jquevremont commented on core/include/riscv_pkg.sv
Shadow performance counters, starting line 468 ``CSR_L1_ICACHE_MISS = 12'hC03,`` need to be updated accordingly.

2023-04-04 12:51 UTC, jquevremont approved these changes
We agreed to defer the gaps to an upcoming PR.

2023-04-05 08:24 UTC, JeanRochCoulon requested changes

2023-04-05 08:24 UTC, JeanRochCoulon commented on core/csr_regfile.sv
> +                riscv::CSR_MHPM_COUNTER_8H :    if (riscv::XLEN == 32) csr_rdata = perf_data_i; else read_access_exception = 1'b1;
From 9H to 31H CSR need to be added, thanks!

2023-04-06 06:30 UTC, merged

2023-04-06 06:30 UTC, JeanRochCoulon commented
Great @TulikaSi !!

2023-04-06 09:04 UTC, JeanRochCoulon commented
Hi @jquevremont @sjthales @TulikaSi 
What a good surprise, we have saved 12kgates in ASIC synthesis after the perf counter merge. Nice !

2023-04-06 12:26 UTC, jquevremont commented
> Hi @jquevremont @sjthales @TulikaSi What a good surprise, we have saved 12kgates in ASIC synthesis after the perf counter merge. Nice !

That's one of the goal. I guess this high number is achieved when performance counters are disabled. You should also have gains (vs. previous version) when you enable them.

2023-04-06 12:29 UTC, jquevremont commented
Can you check they are still in the netlist? It looks huge.

2023-04-14 06:02 UTC, TulikaSi commented
Hi @JeanRochCoulon @jquevremont 
As per the FPGA Utilisation report there has been a reduction in FF after the newer version as can be seen below:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/T0264695/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/T0264695/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl63
	{font-weight:700;}
.xl64
	{white-space:normal;}
-->
</head>

<body link="#0563C1" vlink="#954F72">



  | Total LUTs | FFs
-- | -- | --
CVA6   with older version of perf_counters | 41454 | 32398
CVA6   with newer version of perf_counters | 41525 | 32364



</body>

</html>

2023-04-18 08:18 UTC, jquevremont commented
My 2 cents: check the value of  ``ariane_pkg::PERF_COUNTER_EN`` = ``cva6_config_pkg::CVA6ConfigPerfCounterEn`` in the configuration that is ASIC-synthesized, as the performance counters have been made optional (except ``mcycle`` and ``minstret`` of course).

*Reminder:* performance counters have been extended to 64 bits in CV32A6  to  better comply with RISC-V specifications (``hpmcounter𝑛`` and ``hpmcounter𝑛h``). The introduction of the "generic" counters helps to counter more events while keeping the complexity under control.