Add cva6_params hierachy to allow AXI (easier) configuration
openhwgroup/cva6 pull request #1248
Opened 2023-05-29 14:18 UTC by JeanRochCoulon

@zarubaf @Jbalkind @cfuguet @MikeOpenHWGroup @niwis 

This PR is linked to #1233 

This is a PR to configure CVA6. CVA6_params module has been introduced. The user has the possibility to configure cva6 by modifying the input parameters of cva6_params. They are called "user parameters". The cva6 module is instantiated by cva6_params with more parameters useful to configure cva6: with extra typedefs as axi_ar_chan_t.

I am quite confident the same strategy can be applied on XLEN. Before going further, can you give me feedback on the modification ?   Thanks

2023-05-30 15:24 UTC, cfuguet requested changes
Only one change request on the name of default AXI values in the CVA6 configuration package.
For the rest it looks Ok.
It looks like you remade the same modifications that I did in my pull request, and added the cva6_param module.

2023-05-30 15:24 UTC, cfuguet commented on core/cva6_params.sv
> +  parameter int unsigned AxiUserWidth = cva6_config_pkg::CVA6ConfigDataUserWidth,
I would change the name of AXI parameters from the cva6_config_pkg.
I would name them: CVA6ConfigDefaultAxi*.
This is to remove any ambiguity, because at the end, the actual AXI parameters used are those passed through the CVA6 module at instantiation.

2023-05-30 15:30 UTC, cfuguet commented
One thing is missing though with respect to my PR #1223. I merged the ariane_soc_pkg and the ariane_axi_pkg (removing this last) to simplify the testbench definition. But, of course, this is only for testbench purposes, thus not mandatory.

2023-05-30 15:34 UTC, JeanRochCoulon commented
Oups, what a pity not having started from your PR = waste of time.

Of course the merge of the two packages is better. If it is ok for you, it is possible to increment this PR with your commit.

I will rename the default parameters

2023-06-06 12:57 UTC, JeanRochCoulon commented
@Jbalkind @zarubaf    The solution has been implemented on AXI parameters. The objective would be to handle in the same way all parameters (XLEN for instance). Can you approve it ?

2023-06-07 17:12 UTC, Jbalkind commented
Perhaps it would make sense to migrate `ariane_pkg::ariane_cfg_t ArianeCfg` into this same new module to demonstrate that we can use it for more than the AXI parameters?

Are we sure that tools in general won't have a problem with the structs only being declared in the parameters of that one module? I feel like we should discuss the implications of this particular choice more before adopting it. Perhaps at Tuesday's west shifted meeting?

2023-06-08 05:22 UTC, JeanRochCoulon commented
Let's disccuss the point in the next meeting !

2023-06-13 15:45 UTC, zarubaf commented
I've noted the following points from our meeting just now. Run smoke tests on the following platforms:

- [ ] VCS
- [ ] QuestSim
- [ ] DC Shell
- [ ] Verilator
- [ ] Vivado

And add one more complex configuration:

- [ ] PLEN

2023-06-13 15:52 UTC, zarubaf commented on core/cva6_params.sv
> +  input  wt_cache_pkg::l15_rtrn_t      l15_rtrn_i,
As just discussed:
```suggestion
  output noc_req_t       noc_req_o,
  input  noc_rsp_t      noc_rsp_i
```

2023-06-13 15:52 UTC, zarubaf commented on core/cva6_params.sv
> +  input  axi_rsp_t                     axi_resp_i
```suggestion
```

2023-06-13 15:52 UTC, zarubaf commented on core/cva6_params.sv
> +  parameter type axi_req_t = struct packed {
```suggestion
  parameter type noc_req_t = struct packed {
```

2023-06-13 15:52 UTC, zarubaf commented on core/cva6_params.sv
> +  parameter type axi_rsp_t = struct packed {
```suggestion
  parameter type noc_rsp_t = struct packed {
```

2023-06-13 15:52 UTC, zarubaf commented on core/cva6_params.sv
> +module cva6_params import ariane_pkg::*; #(
I think we can just go directly to the main file :-)
```suggestion
module cva6 import ariane_pkg::*; #(
```

2023-07-26 11:54 UTC, zarubaf commented
The only missing task I can see is:

> And add one more complex configuration:
- [ ] PLEN

Which we will tackle in the next weeks. Closing this, as the majority is already in `master` of this.

2023-07-26 11:54 UTC, closed without merging