Add CVXIF chapter in user's guide
openhwgroup/cva6 pull request #1289
Opened 2023-06-30 14:35 UTC by Gchauvon

Signed-off-by: Guillaume Chauvon <guillaume.chauvon@thalesgroup.com>

2023-06-30 14:39 UTC, JeanRochCoulon commented
@jquevremont    Can you approve the PR ?

2023-06-30 17:21 UTC, jquevremont requested changes
This looks like the design document, not the user's guide. The user will see CVA6 from the outside, connecting a coprocessor on the CV-X-IF interface, setting the needed CVA6 parameters. A second user (or the same) will the use the coprocessor in SW. We should not see any internal functional units nor CVA6 internal signals. I am sorry I had not time enough to review all the details.

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +This design specification presents global functionalities of
This is the user guide, not the design document. It should focus on the CVA6 user: integrators, SW developers... We should not find "inner" information about CVA6.

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/en/core-v-xif_v0.2.0/x_ext.html
Refer to [CV-X-IF] instead. We keep references up to date in the introduction file.

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +* Offload CVA6 illegal instrutions to the coprocessor to be executed.
They are not illegal for the CV-X-IF user.

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +* Kill offloaded instructions to allow speculative execution in the coprocessor.
Is speculative execution supported now?

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +the CVA6 in the execute stage. The cvxif_fu functional unit will get information
The user will only see the CV-X-IF interface. The cvxif_fu shall not be detailed in a user guide, nor the schematic below. These inner details should move to the design document.

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +Inputs/Outputs of CVXIF Functional Unit
We should only have the CV-X-IF signals.

2023-06-30 17:21 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +Illegal instruction decoding
Please focus on the user (SW programmer, HW integrator).

2023-06-30 17:22 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +The following table presents CVXIF parameters supported by CVA6.
Parameters are needed for the user. You can guide them to select the right values.

2023-06-30 17:23 UTC, jquevremont commented on docs/01_cva6_user/CVX_Interface_Coprocessor.rst
> +CVXIF Functional Unit and writeback
Same comments as previously.

2023-07-06 09:43 UTC, jquevremont commented
We had an offline discussion with @Gchauvon. He is preparing an update. Do not merge in the meantime.

2023-08-09 13:49 UTC, jquevremont commented
Good content. I will issue a subsequent PR with typo fixes.

2023-08-09 13:49 UTC, merged