Adding configs for Polara
openhwgroup/cva6 pull request #1309
Opened 2023-07-19 20:13 UTC by hossein1387

This PR includes configs for CVA6 to be used inside Polara project.

2023-07-19 21:11 UTC, JeanRochCoulon commented
Hello @hossein1387   please to meet you.
It seems that your PR has not been rebased. Could you rebase with the newest master branch ?!?  Thanks

2023-07-24 15:21 UTC, Jbalkind commented
Also the PR seems to modify the openpiton config - this shouldn't be the case

2023-07-25 20:31 UTC, hossein1387 commented
@JeanRochCoulon Please to meet you as well. I just rebased my branch. 
@Jbalkind With the new changes, I only have to enable FP16 in CVA6 config. The reason for that is by default, Ara supports half precision and throws an error if CVA6 does not support it. have a look  [here](https://github.com/PolyMTL-Gr2m/ara/blob/ee887bdb20ce396d438639a85bc2640718806fdc/hardware/src/ara.sv#L485). Of course, this may not be the Openpiton's default config and its more of Polara configuration. In that case, should move the configuration to a new file `cv64a6_imafdc_sv39_polara_config_pkg`?

2023-07-26 08:40 UTC, JeanRochCoulon commented
The three files you modify are not used by Thales CI.
LGTM. @zarubaf, as I am out of office up to August 11th, do not hesitate to merge PR (when @hossein1387 is ready to merge).

2023-07-26 08:58 UTC, zarubaf commented
Would it be possible to maintain `cv64a6_imafdc_sv39_polara_config_pkg` outside of CVA6 or do you see a strong reason why it should live here?

@JeanRochCoulon got it.

2023-07-26 09:01 UTC, JeanRochCoulon commented
For info, our long term view is to replace the config package file by the in parameter configuration.

2023-07-26 14:58 UTC, Jbalkind commented
Given Polara is an OpenHW supported tapeout, I'm inclined to say we should put a polara config and let it evaporate with the rest when they do. Maintaining it independently while we're in the tapeout process and the configs keep changing sounds like a pain.

2023-08-06 02:16 UTC, hossein1387 commented
Based on the discussion with @Jbalkind I added a new config file for Polara. After rebasing with master, I noticed that the CVX interface on ariane is not propagated to the interface list. That is required when I need to integrate it with Ara in Openpiton. Please let me know what you think.

2023-08-08 16:14 UTC, Jbalkind requested changes
I think these suggestions might fix the broken CI

2023-08-08 16:14 UTC, Jbalkind commented on corev_apu/src/ariane.sv
> +  parameter type cvxif_resp_t = acc_pkg::accelerator_resp_t,
I think this should probably default to `logic` to fix CI

2023-08-08 16:14 UTC, Jbalkind commented on corev_apu/src/ariane.sv
> +  input cvxif_pkg::cvxif_resp_t        cvxif_resp_i,
I think this should be `cvxif_req_t` and `cvxif_resp_t`, NOT with `cvxif_pkg::`

2023-08-08 16:14 UTC, Jbalkind commented on core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
> +    localparam CVA6ConfigF16En = 1;
Let's not change this

2023-08-08 16:14 UTC, Jbalkind commented on core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
> +    localparam CVA6ConfigVExtEn = 1;
Let's not change this

2023-08-10 04:11 UTC, hossein1387 commented on corev_apu/src/ariane.sv
> +  parameter type cvxif_resp_t = acc_pkg::accelerator_resp_t,
The [issue with](https://github.com/openhwgroup/cva6/actions/runs/5816727072/job/15770256354?pr=1309#step:4:19) CI is adding the `cvx` interface to the port list: [here]( https://github.com/PolyMTL-Gr2m/cva6/blob/cva6-rebase-openpiton/corev_apu/src/ariane.sv#L48)

2023-08-10 04:12 UTC, hossein1387 commented on corev_apu/src/ariane.sv
> +  input cvxif_pkg::cvxif_resp_t        cvxif_resp_i,
Thanks for pointing this out! Yoan found this bug the hard way. Simulation went all fine but in Synthesis, we got port mismatch.

2023-08-10 04:12 UTC, hossein1387 commented on core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
> +    localparam CVA6ConfigF16En = 1;
Done.

2023-08-10 04:25 UTC, hossein1387 commented on corev_apu/src/ariane.sv
> +  parameter type cvxif_resp_t = acc_pkg::accelerator_resp_t,
Given that this is Polara specific change, I removed the `cvx` interface from the port list.

2023-08-13 22:08 UTC, JeanRochCoulon commented
@hossein1387    Can you sign the Eclipse agreement ?   This is the OpenHW process... Thks

2023-08-14 03:37 UTC, hossein1387 commented
> @hossein1387 Can you sign the Eclipse agreement ? This is the OpenHW process... Thks

I already have done that.

2023-08-14 06:02 UTC, JeanRochCoulon commented
Ok... Sometimes when the PR is submitted before signing the agreement, the PR need to be re-submitted. Nevermind, I merge as it is, we will look at it for the next PR. Thanks @hossein1387.

2023-08-14 06:02 UTC, merged