resolving lint warnings...
openhwgroup/cva6 pull request #1529
Opened 2023-10-11 15:36 UTC by fatimasaleem

2023-10-11 16:08 UTC, zarubaf requested changes
lgtm, only some style nits

2023-10-11 16:08 UTC, zarubaf commented on core/cvxif_fu.sv
> +    endgenerate
```suggestion
    if (cvxif_pkg::X_NUM_RS == 3) begin : gen_third_operand 
        assign rs_valid = 3'b111;
    end else begin: gen_no_third_operand
        assign rs_valid = 2'b11;
    end
```

2023-10-11 16:08 UTC, zarubaf commented on core/issue_read_operands.sv
> +    generate
Please remove `generate` and add `begin`/`end`.

2023-10-11 16:08 UTC, zarubaf commented on core/issue_read_operands.sv
> +    generate
Please remove `generate` and add `begin`/`end`.

2023-10-11 16:08 UTC, zarubaf commented on core/issue_read_operands.sv
> +    generate
Please remove `generate` and add `begin`/`end`.

2023-10-11 16:08 UTC, zarubaf commented on core/load_store_unit.sv
> +    generate
Please remove `generate` and add `begin`/`end`.

2023-10-11 16:08 UTC, zarubaf commented on core/scoreboard.sv
> +    generate
Please remove `generate` and add `begin`/`end`.

2023-10-19 08:39 UTC, AEzzejjari commented on core/cache_subsystem/wt_dcache_wbuffer.sv
> +  endgenerate
This modification causes a bug in the AXI interface, you need to remove [1:0] next to the miss_size_o variable.

2023-10-20 13:01 UTC, merged

2023-10-20 13:02 UTC, JeanRochCoulon commented
Nice Fatima, thank for this PR !