Mmu unify - Task1
openhwgroup/cva6 pull request #1725
Opened 2023-12-19 11:24 UTC by AngelaGonzalezMarino

Merge of sv32 and sv39 MMUs. Parametrization strategy followed for new parameters.

2023-12-19 11:30 UTC, AngelaGonzalezMarino commented on core/mmu_unify/cva6_ptw.sv
> +                               be_gen(req_port_o.address_index[2:0], req_port_o.data_size);
Is this the preferred style?

2023-12-19 11:30 UTC, AngelaGonzalezMarino commented on core/mmu_unify/cva6_tlb.sv
> +    // we got a hit so update the pointer as it was least recently used
Other for loops are not separated in lines, I would not do this

2023-12-19 14:41 UTC, fatimasaleem commented
Will we be deleting the old mmu_sv32 & mmu_sv39 directories?

2023-12-19 14:53 UTC, AngelaGonzalezMarino commented
> Will we be deleting the old mmu_sv32 & mmu_sv39 directories?

No, we added a new directory "mmu_unify"

2023-12-19 16:16 UTC, cathales commented on core/mmu_unify/cva6_tlb.sv
> +    // we got a hit so update the pointer as it was least recently used
After [monkeying](https://en.wikipedia.org/wiki/Infinite_monkey_theorem) this section of the code, the issue seems related to the `\` at the end of lines in the comment above…

When it encounters a `\` at the end of a comment, it seems to cumulate the number of characters on all the comment lines until the code line included, including the carriage return bytes between the lines. When it exceeds 110 then it seems to consider that it is too long so it "cuts" the `for` line.

Below is a workaround. It would be good to report the issue to Verible anyway.

```systemverilog
    // | lvl0        0        |
    // |            / \       |
    // |           /   \      |
    // | lvl1     1     2     |
    // |         / \   / \    |
    // | lvl2   3   4 5   6   |
    // |       / \ /\/\  /\   |
    // |      ... ... ... ... |
```

2023-12-19 16:59 UTC, AngelaGonzalezMarino commented on core/mmu_unify/cva6_tlb.sv
> +    // we got a hit so update the pointer as it was least recently used
good catch! It seems this comment is gone after implementing your suggestion

2023-12-19 17:05 UTC, AngelaGonzalezMarino commented on core/mmu_unify/cva6_ptw.sv
> +          be_gen(req_port_o.address_index[2:0], req_port_o.data_size);
this seems also gone now (I added // at the end of the lines that are split)
@cathales is this expected or should also be reported?

2023-12-20 08:58 UTC, cathales requested changes

2023-12-20 08:58 UTC, cathales commented on core/mmu_unify/cva6_ptw.sv
> +          be_gen(req_port_o.address_index[2:0], req_port_o.data_size);
I think it was better without the empty comments.

2023-12-20 09:08 UTC, cathales commented on core/mmu_unify/cva6_ptw.sv
> +                               be_gen(req_port_o.address_index[2:0], req_port_o.data_size);
Unlike the `for` case discussed before, this one does not seem buggy so I’m okay with this style :)

It seems Verible has open issues about it https://github.com/chipsalliance/verible/issues?q=is%3Aissue+ternary but there was no activity on them since Feb 2022.

2023-12-20 09:09 UTC, cathales commented on core/mmu_unify/cva6_tlb.sv
> +    // we got a hit so update the pointer as it was least recently used
Glad to help! Can you mark this discussion as resolved, please?

2023-12-20 10:21 UTC, AngelaGonzalezMarino commented on core/mmu_unify/cva6_ptw.sv
> +          be_gen(req_port_o.address_index[2:0], req_port_o.data_size);
agree, I was trying to get rid of the verible comment but no success in this case

2023-12-20 14:43 UTC, cathales commented on core/mmu_unify/cva6_ptw.sv
> +          be_gen(req_port_o.address_index[2:0], req_port_o.data_size);
This seems to be the last formatting indication

2023-12-21 07:38 UTC, fatimasaleem commented
> > Will we be deleting the old mmu_sv32 & mmu_sv39 directories?
> 
> No, we added a new directory "mmu_unify"

I think we should think about moving the previous module files to some separate directory maybe named as `/deprecated` ? just to avoid confusion.

2023-12-21 08:15 UTC, JeanRochCoulon commented
I definitely encourage you to remove the deprecated files from the repository to avoid confusion. Everybody must adopt the new code.

2023-12-21 09:39 UTC, AngelaGonzalezMarino commented
Ok, should we do this already in this PR or in the next one with the whole MMU supporting hypervisor? Where should this deprecated folder go? Thanks!

2023-12-21 09:44 UTC, cathales commented
IMO if you are *moving* code is it good to remove the old files in the same PR as you add the new files.

It makes it easier to find out where do things come from: as you follow history backwards, you find which commit/PR created a file and notice that in the same commit/PR other files were removed. If we wait and remove things later, we will not have this relationship.

2023-12-21 11:59 UTC, fatimasaleem commented
> IMO if you are _moving_ code is it good to remove the old files in the same PR as you add the new files.
> 
> It makes it easier to find out where do things come from: as you follow history backwards, you find which commit/PR created a file and notice that in the same commit/PR other files were removed. If we wait and remove things later, we will not have this relationship.

I also agree with this approach.

2024-01-24 13:35 UTC, jquevremont commented
Trial PR (to get CI, linting feedback). Marked "Do not merge". Will be updated when MMU unification has progressed.

2024-02-20 13:22 UTC, JeanRochCoulon commented
Superseeded by #1851

2024-02-20 13:22 UTC, closed without merging