Bump `core-v-verif d94f0de` and fix questa simulator
openhwgroup/cva6 pull request #1915
Opened 2024-03-11 11:42 UTC by MarioOpenHWGroup

* Adapt to the new core-v-verif `d94f0de`
* Fix `questa-testharness`, it works now with `2023.1_2`
* Add `questa-uvm` simulator, it does not work now
* `veri-testharness` fix `uvm_macros`

2024-03-11 11:43 UTC, MarioOpenHWGroup commented
Sorry to fix the questa simulator in the same PR but I do not have currently access to vcs :cry:

2024-03-21 16:53 UTC, valentinThomazic requested changes

2024-03-21 16:53 UTC, valentinThomazic commented on .gitlab-ci.yml
> +    - source /opt/questa/questa_sim-2022.4_2/questasim/setup/bashrc
TODO : delete

2024-03-21 16:53 UTC, valentinThomazic commented on Makefile
> +	$(VOPT) $(vopt_flags) -64 -work $(library)  $(top_level) -o $(top_level)_optimized +acc -check_synthesis -dpilib $(SPIKE_INSTALL_DIR)/lib/libriscv -dpilib $(SPIKE_INSTALL_DIR)/lib/lifesvr -suppress
TODO : erase

2024-03-21 16:53 UTC, valentinThomazic commented on corev_apu/tb/common/spike.sv
> +                    `GET_RVFI_CSR (CSR_MSTATUS  , mstatus     , 0)
TODO: fix spacing

2024-03-21 16:53 UTC, valentinThomazic commented on corev_apu/tb/rvfi_tracer.sv
> +            if (TOHOST_ADDR != '0 &&
TODO: Delete this

2024-03-21 16:53 UTC, valentinThomazic commented on verif/tb/core/custom_uvm_macros.svh
> +    "UVM_NONE" : 0,
TODO: Align

2024-03-21 16:53 UTC, valentinThomazic commented on verif/tb/uvmt/uvmt_cva6_tb_ifs.sv
> +
TODO: Delete newlines

2024-03-21 18:02 UTC, merged