Parameterization and other fixes for downstream project
openhwgroup/cva6 pull request #1950
Opened 2024-03-21 16:30 UTC by zarubaf

I've encountered some smaller problems when trying to update. Mostly Bender file lists, etc. that shouldn't affect the majority of users here.

Additionally I've fixed some verilator lint warnings as we run a stricter lint deck in-house.

2024-03-22 07:26 UTC, JeanRochCoulon commented
To fix the Verible warning, the command is 
![image](https://github.com/openhwgroup/cva6/assets/56552370/db9a4c59-3265-4c32-81d7-41f4d6c6d534)

2024-03-22 07:39 UTC, zarubaf commented
> To fix the Verible warning, the command is ![image](https://private-user-images.githubusercontent.com/56552370/315921161-db9a4c59-3265-4c32-81d7-41f4d6c6d534.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTMzMTgsIm5iZiI6MTcxMTA5MzAxOCwicGF0aCI6Ii81NjU1MjM3MC8zMTU5MjExNjEtZGI5YTRjNTktMzI2NS00YzMyLTgxZDctNDFmNGQ2YzZkNTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZWUwNGIwNGY5NmIzZGZjMDVlYWFmZjZlYmE3NzM3ZjU5NjFmOTFlZmFkZDlkYThjOWI1NDQ1MWNjOWY0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sSI_T8MGMg9It1RTVQQsgX66ZCdbzp5ilwqmJ1EA-JY)

Do we want to fix this verible issues? And which one do we want to fix? Only data cache?

2024-03-22 08:38 UTC, JeanRochCoulon commented
All files contained in cva6/core/ should be fixed by Verible

2024-03-25 09:11 UTC, cathales requested changes
Review of parametrization-related things.

2024-03-25 09:11 UTC, cathales commented on core/cva6_fifo_v3.sv
This file is added, but the originating file is not reverted to its initial state from `common_cells`. Is it what you meant to do?

2024-03-25 09:11 UTC, cathales commented on core/include/build_config_pkg.sv
> +    cfg.NonIdemPotenceEn = (CVA6Cfg.NrNonIdempotentRules > 0) && (CVA6Cfg.NonIdempotentLength > 0);
:+1:

2024-03-25 09:11 UTC, cathales commented on core/include/config_pkg.sv
> +  localparam cva6_cfg_t cva6_cfg_empty = cva6_cfg_t'(0);
:+1:

2024-03-25 10:23 UTC, zarubaf commented on core/amo_buffer.sv
> +  cva6_fifo_v3 #(
I know. Parameterization just surfaced this. It is quite important with the vendoring that people don't start patching things up in an uncontrolled way w/o upstreaming.

2024-03-25 10:35 UTC, zarubaf commented on core/cva6_fifo_v3.sv
Good idea, reverted.

2024-03-25 10:35 UTC, zarubaf commented on core/axi_shim.sv
> +  if (CVA6Cfg.AXI_USER_EN > 0) begin
Changed to `bit`, change reverted.

2024-03-25 11:14 UTC, cathales commented on core/axi_shim.sv
> +  if (CVA6Cfg.AXI_USER_EN > 0) begin
Doesn’t it complain similarly as it did for you here?

https://github.com/openhwgroup/cva6/blob/ba3558801564b9ade0663f8d45ef7667819d32b6/core/include/build_config_pkg.sv#L129

Because of `int unsigned ...En` here:

https://github.com/openhwgroup/cva6/blob/ba3558801564b9ade0663f8d45ef7667819d32b6/core/include/config_pkg.sv#L161-L166

Maybe we need this instead:

```systemverilog
    // TODO
    bit                          DataUserEn;
    // TODO
    int unsigned                 FetchUserWidth;
    // TODO
    bit                          FetchUserEn;
```

```systemverilog
    cfg.AXI_USER_EN = CVA6Cfg.DataUserEn || CVA6Cfg.FetchUserEn;
```

2024-04-05 09:57 UTC, zarubaf commented
There are two other fixes that were needed for questa to understand the nested typedef structs. They are sometimes not that well supported.

/cc @domenicw

2024-04-05 11:02 UTC, merged