Fix `SuperScalar` config and add `CVA6Cfg` to first pass decoder
openhwgroup/cva6 pull request #2047
Opened 2024-04-16 11:18 UTC by zarubaf

2024-04-16 13:24 UTC, cathales requested changes
So this PR addresses two topics:

1. It passes `CVA6Cfg` to first pass decoder
2. It fixes some Verilator warnings about superscalar modifications. I’m wondering:

    - Is it better to perform changes on the fly like this? It makes PRs more little and keeps the code base clean, but it will likely trigger conflicts with the subsequent superscalar-related PRs.
    - Is it better to collect the issues so that we definitely fix them once superscalar is completely merged, on July 5th? Because parametrization will have to be applied here.

2024-04-16 13:24 UTC, cathales commented on core/frontend/instr_queue.sv
> +  localparam NID = ariane_pkg::SUPERSCALAR > 0 ? 1 : 0;
So this is just `localparam NID = ariane_pkg::SUPERSCALAR`.

Also, IIUC this is not a real "next index". It is just a workaround so that Verilator does not cry because of out-of-range issues.

2024-04-16 13:24 UTC, cathales commented on core/frontend/instr_queue.sv
> +        // TODO handle fetch_entry_o[NID] if superscalar
IMHO "1" is more clear than "NID". Anyway this comment will disappear soon so this change would just create a conflict for me to fix.

```suggestion
        // TODO handle fetch_entry_o[1] if superscalar
```

2024-04-16 13:24 UTC, cathales commented on core/frontend/instr_queue.sv
> +        if (ariane_pkg::SUPERSCALAR > 0) begin
Well yes 😅  When we actually parametrize `SuperscalarEn`, we will likely define both `int unsigned PIPELINE_WITH` and `bit SuperscalarEn`.

2024-04-16 14:50 UTC, zarubaf commented
I can split up the thing in two PRs, but I would really prefer if we can merge the fixed to the superscalar parameterization. I am running behind with the bumping of CVA6 for a couple of weeks now since every day stuff is changing which breaks the instantiation.

2024-04-16 14:51 UTC, zarubaf commented on core/frontend/instr_queue.sv
> +  localparam NID = ariane_pkg::SUPERSCALAR > 0 ? 1 : 0;
Ah I thought superscalar can be more than 1.

2024-04-16 15:15 UTC, cathales commented
IMO if we keep both changes we can have them in this same PR.

I have taken notes for the future definitive fixes so we can merge this.

Still, I find it really sad that despite the explicit `if` blocks to filter Superscalar-related stuff, Verilator does not understand that the things inside the blocks do not exist. I hope at least code coverage tools will understand.

2024-04-17 10:40 UTC, zarubaf commented
> IMO if we keep both changes we can have them in this same PR.
> 
> I have taken notes for the future definitive fixes so we can merge this.
> 
> Still, I find it really sad that despite the explicit `if` blocks to filter Superscalar-related stuff, Verilator does not understand that the things inside the blocks do not exist. I hope at least code coverage tools will understand.

I agree, but I am afraid that if `verilator` already struggles I am unsure what Spyglass and similar tools will say. Let's cross the bridge once we are there.

If you are okay with leaving everything in this PR, I should have addressed your concerns (committed the changes). And I also saw that you took notice about the parameterization. Are you okay with merging?

2024-04-17 14:34 UTC, merged