Address translation request moved from icache to frontend
openhwgroup/cva6 pull request #2084
Opened 2024-04-30 08:28 UTC by yanicasa

In order to aligned the ways address translation is managed between FETCH and DATA the address translation request is moved from the icache to the frontend.

The change is supposed to be transparent, no functional impact, same perf, same critical path...

2024-04-30 08:57 UTC, yanicasa commented
@cfuguet can you review this PR, maybe this modif could be useful if you are planning to design an HPICache for CVA6

2024-04-30 09:34 UTC, cfuguet requested changes

2024-04-30 09:34 UTC, cfuguet commented on core/cva6.sv
> +      logic                    kill_req;           // kill the last request
This is more a note for me while I take a look on all files: Why do you need an additional kill signal ?

2024-04-30 09:34 UTC, cfuguet commented on core/cva6.sv
> -      exception_t                          ex;     // we've encountered an exception
I agree that the previous version of the Icache did not forward any error from the NoC interface (bad address access for example). However, I think it should... Hence, I would recommend to leave this field of the response, an use it to forward an error to the fetch unit.

For this PR, probably you can force it to 0, so you only modify a single functionality, but it can be used in another PR to support this error forwarding.

2024-04-30 09:41 UTC, cfuguet commented on core/cva6.sv
> +      logic                    kill_req;           // kill the last request
With my comment below regarding the handling of an address translation exception, this field (kill_req) should not be needed anymore.

2024-04-30 09:42 UTC, cfuguet commented
Hi @yanicasa, I left you some comments

Best regards

2024-04-30 09:47 UTC, yanicasa commented on core/cva6.sv
> +      logic                    kill_req;           // kill the last request
Maybe this could be merged with kill_s2 but this has an impact on the icache FSM READ state description and I wanted to be conservative.

This new icache kill_req follows the same principle as the dcache kill_req, it is an abort caused by an MMU exception during address translation

Note: the copy paste "// kill the last request" should me updated.

2024-04-30 09:51 UTC, cfuguet commented on core/cva6.sv
> +      logic                    kill_req;           // kill the last request
I would merge with the kill_s1. The exception is valid one cycle after the address translation request. I think there should not be any significant modification in the Icache FSM when doing that

2024-04-30 09:53 UTC, yanicasa commented on core/cva6.sv
> -      exception_t                          ex;     // we've encountered an exception
In fact this field was only used to forward the MMU exception towards the frontend, since it was the cache which received the response from the MMU.
I removed it in symmetry with the Dcache because Dcache also does not send any exception to the LSU.

If we add exception filed for Icache, we would have to do it for Dcache too, maybe it could be done in a dedicated PR if required?

2024-04-30 10:04 UTC, yanicasa commented on core/cache_subsystem/cva6_icache.sv
> +          end else if (((|cl_hit && cache_en_q) || dreq_i.kill_req) && !inv_q) begin
I will to check to remove one of the 3 kill signals which actually seems to be superfluous.

On the other hand, the kill_req for me comes in second time and I have the impression that it will be more linked to kill_s2 than kill_s1, what do you think?

The problem I had with the kill_s2 is that it is used in the frontend to flush the realigned instruction. mixing it with the valid exception, it did weird things but I agree it seem to be possible to manage it in front end.

2024-04-30 10:17 UTC, cfuguet commented on core/cva6.sv
> -      exception_t                          ex;     // we've encountered an exception
Yes, I agree. We can do a different PR to support that

2024-05-01 21:20 UTC, JeanRochCoulon commented
@yanicasa @cfuguet  I would prefer to move step by step. As the first goal of the PR was to move the address translation request from icache to frontend, can we merge this modification before submitting another PR to improve even more the design ?

2024-05-02 05:27 UTC, cfuguet commented
IMHO, adding a third kill signal to the instruction fetch interface is adding more complexity. And it is kind of still leaving a part of the address translation mechanism in the Icache.

2024-06-03 06:50 UTC, JeanRochCoulon commented
Superseeded by #2179

2024-06-03 06:50 UTC, closed without merging