Interrupt verif : Implement clear mechanism in interrupt's agent
openhwgroup/cva6 pull request #2527
Opened 2024-10-04 11:00 UTC by AyoubJalali

This MR implement set/clear interrupt based on protocol in https://gitlab-tss.gemalto.com/riscv/cva6/-/blob/master/verif/docs/Protocols/interrupt-verification.adoc?ref_type=heads

2024-10-09 10:03 UTC, AyoubJalali commented
Hello @MikeOpenHWGroup, Could you please take a look ?

2024-10-10 16:47 UTC, MikeOpenHWGroup requested changes
Whew!  A very impressive contribution @AyoubJalali!  I am especially happy to see you using the templated RESET run-flow.  I have made a few comments on specific files, but in general this is really great stuff.

2024-10-10 16:47 UTC, MikeOpenHWGroup commented on verif/env/corev-dv/cva6_asm_program_gen.sv
> +             // CSR values are set properly. The checking is done by comparing against the log
> The checking is done by comparing against the log generated by ISA simulator (spike).

This is _not_ true in UVM environment of CORE-V-VERIF. In CVV, the checking is down by lock-step comparisons against the Spike-Tandem reference model.

2024-10-10 16:47 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +task automatic uvma_interrupt_seq_c::clear_irq_channel(int channel, uvma_interrupt_seq_item_c  req_item);
There is an opportunity for deadlock here if the test-program fails to write `irq_addr`.   Recommend that this task should call `uvm_fatal()` after some "reasonable" number of cycles.

2024-10-10 16:47 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +                      assert(req_item_c.randomize() with {
Please do not use `assert` for checking for successful randomization.  If/when randomization fails, the `assert` will produce a simulator-dependent error message and this will not be "seen" by the UVM messaging service and the simulation may pass with a false positive.

A better implementation is as follows:
```
if (!req_item_c.randomize() with {
                      req_item_c.interrupt_vector[ii] inside {0 , 1};
                      req_item_c.interrupt_channel_mask == 1<<ii;
                      })
   `uvm_error(get_type_name(), "req_item_c.randomize() failed!")
```

2024-10-10 16:47 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +     `uvm_warning(get_type_name(), $sformatf("Interrupts are disabled"));
Should this be a warning?  A lot of tests will be run without interrupts.

2024-10-10 16:47 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/uvma_interrupt_mon.sv
> +      `uvm_fatal("build_phase", "monitor cntxt class failed")
The `ID` argument should be set to easily identify the source of the message.  "build_phase" is implemented by many uvm_components, so this is probably not useful.   Recommend using either `get_type_name()` or some string that makes it easy to find the source of the message (maybe "INTR_MON"?).

2024-10-10 16:47 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/uvma_interrupt_mon.sv
> +      `uvm_fatal("CFG", "Configuration handle is null")
Same comment.

2024-10-11 09:02 UTC, AyoubJalali commented
Thanks @MikeOpenHWGroup 
I'm on it !

2024-10-11 10:51 UTC, AyoubJalali commented
I make the changes requested @MikeOpenHWGroup, but i had a git problem trying to update this branch
I'll create a new PR with the changes requested
I'll close this one when the other PR is ready

2024-10-11 14:38 UTC, AyoubJalali commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +     `uvm_warning(get_type_name(), $sformatf("Interrupts are disabled"));
This is just to help for debug, if any one run a interrupt test without enabling interrupt, it gives a warning

2024-10-11 14:40 UTC, AyoubJalali commented
I rebase the branch, also I applied also your suggestions, thanks

2024-10-11 14:59 UTC, AyoubJalali commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +task automatic uvma_interrupt_seq_c::clear_irq_channel(int channel, uvma_interrupt_seq_item_c  req_item);
I had this idea, but i didn't have this "reasonable" number of cycle, so I let it go like that in first place, but i'll consider it

2024-10-15 12:55 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +task automatic uvma_interrupt_seq_c::clear_irq_channel(int channel, uvma_interrupt_seq_item_c  req_item);
There are two related questions here:
1.  **What is a "reasonable timeout value?** 
A typical "reasonable-response-timeout" is the average length of a test.  I am not certain about this, but I would guess that it should be 100_000 clock cycles.
3. **How to implement it?**
The timeout should be a random member of the Agent's configuration object and there should be a soft constraint to define a reasonable value.  That way, the timeout can be easily controlled from a `uvm_testcase`.

2024-10-15 13:00 UTC, MikeOpenHWGroup commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +     `uvm_warning(get_type_name(), $sformatf("Interrupts are disabled"));
No, this is not correct.  Warnings are reported in the `report` phase and we cannot sign-off TRL-5 if there are warnings.  So this should be a `uvm_info()`, not `uvm_warning()`.

2024-10-16 10:00 UTC, AyoubJalali commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +task automatic uvma_interrupt_seq_c::clear_irq_channel(int channel, uvma_interrupt_seq_item_c  req_item);
I implement TIMEOUT variable, I suggest to only give 10_000 clock cycle after exit the simulation

2024-10-16 10:00 UTC, AyoubJalali commented on verif/env/uvme/uvma_interrupt/seq/uvma_interrupt_seq.sv
> +     `uvm_warning(get_type_name(), $sformatf("Interrupts are disabled"));
Done

2024-10-16 15:25 UTC, MikeOpenHWGroup approved these changes

2024-10-16 15:50 UTC, merged