Adding support for ZCMT Extension for Code-Size Reduction in CVA6
openhwgroup/cva6 pull request #2659
Opened 2024-12-10 09:55 UTC by farhan-108

## Introduction
This PR implements the ZCMT extension in the CVA6 core, targeting the 32-bit embedded-class platforms. ZCMT is a code-size reduction feature that utilizes compressed table jump instructions (cm.jt and cm.jalt) to reduce code size for embedded systems
**Note:** Due to implementation complexity, ZCMT extension is primarily targeted at embedded class CPUs. Additionally, it is not compatible with architecture class profiles.(Ref. [Unprivilege spec 27.20](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view))

## Key additions

- Added zcmt_decoder module for compressed table jump instructions: cm.jt (jump table) and cm.jalt (jump-and-link table)

- Implemented the Jump Vector Table (JVT) CSR to store the base address of the jump table in csr_reg module

- Implemented a return address stack, enabling cm.jalt to behave equivalently to jal ra (jump-and-link with return address), by pushing the return address onto the stack in zcmt_decoder module

## Implementation in CVA6
The implementation of the ZCMT extension involves the following major modifications:

### compressed decoder 
The compressed decoder scans and identifies the cm.jt and cm.jalt instructions, and generates signals indicating that the instruction is both compressed and a ZCMT instruction.

### zcmt_decoder
A new zcmt_decoder module was introduced to decode the cm.jt and cm.jalt instructions, fetch the base address of the JVT table from JVT CSR, extract the index and construct jump instructions to ensure efficient integration of the ZCMT extension in embedded platforms. High-level block diagram of zcmt implementation in CVA6 is shown in Figure 1.

### branch unit condition
A condition is implemented in the branch unit to ensure that ZCMT instructions always cause a misprediction, forcing the program to jump to the calculated address of the newly constructed jump instruction.

### JVT CSR
A new JVT csr is implemented in csr_reg which holds the base address of the JVT table. The base address is fetched from the JVT CSR, and combined with the index value to calculate the effective address.

### No MMU
Embedded platform does not utilize the MMU, so zcmt_decoder is connected with cache through port 0 of the Dcache module for implicit read access from the memory.

![zcmt_block drawio](https://github.com/user-attachments/assets/ac7bba75-4f56-42f4-9f5e-0c18f00d4dae)
_Figure. 1 High level block diagram of ZCMT extension implementation_

## Known Limitations
The implementation targets 32-bit instructions for embedded-class platforms without an MMU. Since the core does not utilize an MMU, it is leveraged to connect the zcmt_decoder to the cache via port 0.

## Testing and Verification

- Developed directed test cases to validate cm.jt and cm.jalt instruction functionality
- Verified correct initialization and updates of JVT CSR

### Test Plan 
A test plan is developed to test the functionality of ZCMT extension along with JVT CSR. Directed Assembly test executed to check the functionality. 

S.no | Features | Description | Pass/Fail Criteria | Test Type | Test status
-- | -- | -- | -- | ---- | --
1 | cm.jt | Simple assembly test to validate the working of cm.jt instruction in  CV32A60x. | Check against Spike's ref. model | Directed | Pass
2 | cm.jalt | Simple assembly test to validate the working of cm.jalt instruction in both CV32A60x. | Check against Spike's ref. model | Directed | Pass
3 | cm.jalt with return address stack | Simple assembly test to validate the working of cm.jalt instruction with return address stack in both CV32A60x. It works as jump and link ( j ra, imm) | Check against Spike's ref. model | Directed | Pass
4 | JVT CSR | Read and write base address of Jump table to JVT CSR | Check against Spike's ref. model | Directed | Pass

**Note**: Please find the test under CVA6_REPO_DIR/verif/tests/custom/zcmt"

2024-12-10 09:57 UTC, JeanRochCoulon commented
@yanicasa

2024-12-10 10:00 UTC, JeanRochCoulon commented
@ASintzoff

2024-12-10 10:55 UTC, fatimasaleem commented
Hi @JeanRochCoulon how can we know which line in the code this spyglass failure refers to? 'Some inputs to instance are not driven or unconnected'

2024-12-10 10:59 UTC, JeanRochCoulon commented
@ASintzoff    do you know how to help ?

2024-12-11 12:24 UTC, fatimasaleem commented
> @ASintzoff do you know how to help ?
 
@JeanRochCoulon 
@farhan-108 found the issue and resolved it. Now only failure is due to the gate count increase.

2024-12-11 12:44 UTC, ASintzoff commented
> > @ASintzoff do you know how to help ?
> 
> @JeanRochCoulon @farhan-108 found the issue and resolved it. Now only failure is due to the gate count increase.

is the extension completely optional? All the RTL added for Zcmt should be removed when the extension is not set. If not, it can increase the gate count.

2024-12-11 16:41 UTC, JeanRochCoulon commented on core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
Can you remove this unused localparam ?

2024-12-11 17:13 UTC, JeanRochCoulon commented on core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:21 UTC, JeanRochCoulon commented on core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:21 UTC, JeanRochCoulon commented on core/include/cv32a6_imac_sv0_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:21 UTC, JeanRochCoulon commented on core/include/cv32a6_imac_sv32_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:22 UTC, JeanRochCoulon commented on core/include/cv32a6_imafc_sv32_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:22 UTC, JeanRochCoulon commented on core/include/cv64a6_imafdc_sv39_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:22 UTC, JeanRochCoulon commented on core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:22 UTC, JeanRochCoulon commented on core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:22 UTC, JeanRochCoulon commented on core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:23 UTC, JeanRochCoulon commented on core/include/cv64a6_imafdch_sv39_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 17:23 UTC, JeanRochCoulon commented on core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
> +  localparam CVA6ConfigZcmtExtEn = 0;
```suggestion
```

2024-12-11 22:13 UTC, JeanRochCoulon commented on core/id_stage.sv
> +    if (CVA6Cfg.RVZCMP || (CVA6Cfg.RVZCMT & ~CVA6Cfg.MmuPresent)) begin //MMU should be off when using ZCMT
I bet 2 cents that the gate count increase comes from this condition: decoder_macro and zcmt_decoder are both inferred by the same if condition. To me, decoder_macro depends on zcmp and zcmt_decoder depends on zcmt.

2024-12-12 11:54 UTC, fatimasaleem commented on core/id_stage.sv
> +    if (CVA6Cfg.RVZCMP || (CVA6Cfg.RVZCMT & ~CVA6Cfg.MmuPresent)) begin //MMU should be off when using ZCMT
@JeanRochCoulon almost ~1k gate count is increased in issue_stage, which I think is because we added one signal in scoreboard struct.

2024-12-12 11:56 UTC, fatimasaleem commented on core/id_stage.sv
> +    if (CVA6Cfg.RVZCMP || (CVA6Cfg.RVZCMT & ~CVA6Cfg.MmuPresent)) begin //MMU should be off when using ZCMT
I suggest we increase the expected_synth gate count. What do you think, @JeanRochCoulon?

2024-12-16 15:34 UTC, cathales requested changes
Thank you for your contribution. Here are some suggestions.

By the way, do you think it would be feasible to make it compatible with superscalar?

Also, there is still the area increase which is really impacting even when it is disabled at elaboration time.

2024-12-16 15:34 UTC, cathales commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
This does not work if the target address is too far from the current program counter.

2024-12-17 09:02 UTC, farhan-108 commented on core/zcmt_decoder.sv
@cathales i have run this command.

2024-12-17 09:03 UTC, farhan-108 commented on core/zcmt_decoder.sv
> +    output dcache_req_i_t        req_port_o        // Data cache request input - CACHE
@cathales I have updated the description and added the IO port connection table.

2024-12-17 09:03 UTC, farhan-108 commented on core/zcmt_decoder.sv
> +              5'h1,
@cathales The resolved_branch signal is updated in the branch unit, ensuring that the RAS is also updated and enabling jump on calculated address instead of predicted address.

2024-12-17 09:14 UTC, farhan-108 commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
@cathales This mechanism supports jumps within a range of ±1 MB from the current program counter, as the addr_jump field uses 20 bits as an offset immediate from the PC, it is similar to the JAL instruction in 32-bit RISC-V.

2024-12-17 09:16 UTC, farhan-108 commented
> Thank you for your contribution. Here are some suggestions.
> 
> By the way, do you think it would be feasible to make it compatible with superscalar?
> 
> Also, there is still the area increase which is really impacting even when it is disabled at elaboration time.

@cathales Currently, it is not compatible with a superscalar architecture because it stalls the pipeline in the decode stage until the implicit fetch is completed. Compatibility will be addressed in a future update alongside the ZCMP extension.

2024-12-17 09:42 UTC, cathales commented on core/decoder.sv
> +    //zcmt instruction
```suggestion
    // Zcmt instruction - FRONTEND
```

2024-12-17 09:42 UTC, cathales commented on core/include/config_pkg.sv
> +    assert (!(Cfg.SuperscalarEn && Cfg.RVZCMT && ~CVA6Cfg.MmuPresent));
`Cfg.SuperscalarEn && Cfg.RVZCMT` won’t trigger this assertion. You could split into two distinct assertions:

```suggestion
    assert (!(Cfg.SuperscalarEn && Cfg.RVZCMT));
    assert (!(Cfg.RVZCMT && ~CVA6Cfg.MmuPresent));
```

2024-12-17 09:42 UTC, cathales commented on core/branch_unit.sv
> +          resolved_branch_o.cf_type = ariane_pkg::Jump;
We could send a `JumpR` instead of `Jump`. It would update BTB in the frontend to correctly predict the destination next time.
We could then calculate `is_mispredict` accordingly, to use this prediction when we later encounter the same `cm.jt` or `cm.jalt`.

2024-12-17 09:42 UTC, cathales commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
Because of this limitation, this implementation is not compliant with Zcmt, is it?

2024-12-17 09:45 UTC, cathales commented on core/zcmt_decoder.sv
> +              5'h1,
AFAIU, `resolved_branch` has no influence on the RAS as of f4355fa49b6ed592579146dbfc65a34f3bbd6ed2

[cva6/core/frontend/frontend.sv at f4355fa49b6ed592579146dbfc65a34f3bbd6ed2 · openhwgroup/cva6](https://github.com/openhwgroup/cva6/blob/f4355fa49b6ed592579146dbfc65a34f3bbd6ed2/core/frontend/frontend.sv)

Instead, the frontend could be modified:

- `intsr_scan` could detect that it is a call
- this call detection would rise `ras_push`
- this `ras_push` signal would push the correct address into the RAS

2024-12-17 09:52 UTC, farhan-108 commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
@cathales according to ZCMT spec cm.jt and cm.jalt is equivalent to 
• 32-bit j calls
• 32-bit jal ra calls
and J / jal ra calls only jump to ±1 MB
Thus implementation is complaint with zcmt as it is only for 32 bits.

2024-12-17 09:54 UTC, cathales commented on core/zcmt_decoder.sv
> +    output dcache_req_i_t        req_port_o        // Data cache request input - CACHE
I cannot see it as of 2124fa662a27a0cf9f24a9c168a1fa85e50bddef.

The expected format is:

- A line with only a comment, before the port declaration
- In the comment, the port description followed by " - " and the connection

For instance:

```systemverilog
// Data cache request input - CACHE
output dcache_req_i_t req_port_o
```

Not:

```systemverilog
output dcache_req_i_t req_port_o // Data cache request input - CACHE
```

Nor:

```systemverilog
// Data cache request input
output dcache_req_i_t req_port_o
```

2024-12-17 11:09 UTC, ASintzoff commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
At https://github.com/riscv/riscv-isa-manual/blob/main/src/zc.adoc#table-jump-overview RISC-V specification states 
> cm.jt and cm.jalt encodings index the table, giving access to functions within the full XLEN wide address space.

Therefore, the target addresses shall be any address and not only addresses _near_ the current PC.

2024-12-17 12:18 UTC, cathales commented on core/include/config_pkg.sv
> +    assert (!(Cfg.SuperscalarEn && Cfg.RVZCMT && ~CVA6Cfg.MmuPresent));
Also, the jobs fail because it should be `Cfg` instead of `CVA6Cfg` here.

2024-12-19 14:29 UTC, JeanRochCoulon commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
A possibility is to write the table address into the scoreboard result field, and give this result field as input of the functional unit. In that way, address can be within the full XLEN wide address space, that is to say 32 bits.

2025-01-03 10:39 UTC, JeanRochCoulon commented
Hello @farhan-108  
Happy New Year !
I reviewed the PR. Can you update the expected gate count value, rebase and status about comments?
Cheers

2025-01-03 13:35 UTC, farhan-108 commented on core/zcmt_decoder.sv
> +          jump_addr = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
@JeanRochCoulon 
I have updated the code to support a full XLEN-wide jump implementation and added basic long jump tests as well.

2025-01-07 07:57 UTC, JeanRochCoulon commented on core/id_stage.sv
> +        .jump_address_i            (jump_address),
Spyglass reports this new Warning :
![image](https://github.com/user-attachments/assets/346b1abe-8f33-4f8f-8dcb-32cd71f91d79)

2025-01-07 09:46 UTC, farhan-108 commented on core/id_stage.sv
> +        .jump_address_i            (jump_address),
@JeanRochCoulon 
Warning resolved.

2025-01-09 13:35 UTC, cathales reviewed
This PR seems compliant with the spec now.
Here are a few suggestions for code clarity and gates optimization.

About branch prediction:

It seems we would have branch misses on all Zcmt instruction (mispredict hardwired to 1 in branch_unit) + on the `ret` to get out of the Zcmt-called function (no RAS updates from instr_scan in the frontend). It can wait for a later PR.

IMHO branch prediction should not be a requirement for this PR and can be added later.

2025-01-09 13:35 UTC, cathales commented on core/zcmt_decoder.sv
> +            table_address = {2'b00, ({jvt_i.base, jvt_i.mode} + {24'h0, instr_i[7:2], 2'b00})};
```suggestion
            table_address = {jvt_i.base, 6'0} + {24'h0, instr_i[7:2], 2'b00};
```

Using 0 instead of `jvt_i.mode` should be more future-proof.
Also, let’s split the logic with the address calculation on VLEN on the one hand, and the translation/PLEN extension on the other hand.

2025-01-09 13:35 UTC, cathales commented on core/zcmt_decoder.sv
> +            req_port_o.address_tag = table_address[33:10];
```suggestion
            req_port_o.address_tag = table_address[CVA6Cfg.VLEN-1:10]; // No MMU support
```

2025-01-09 13:35 UTC, cathales commented on core/zcmt_decoder.sv
> +    is_compressed_o       = is_zcmt_instr_i ? 1'b1 : is_compressed_i;
```suggestion
    is_compressed_o       = is_zcmt_instr_i || is_compressed_i;
```

2025-01-09 13:35 UTC, cathales commented on core/zcmt_decoder.sv
> +    fetch_stall_o         = is_zcmt_instr_i ? 1'b1 : 0;
```suggestion
    fetch_stall_o         = is_zcmt_instr_i;
```

It looks strange that the output equals the input… Shouldn’t it be driven from the state?

2025-01-09 13:35 UTC, cathales commented on core/include/riscv_pkg.sv
> +  } jvt_t;
```suggestion
```

This seems to be an unused duplicate of the `localparam type jvt_t` defined in `cva6.sv`.

2025-01-16 12:32 UTC, farhan-108 commented on core/zcmt_decoder.sv
> +          jump_address_o = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
@cathales 
Thank you for your suggestion. I believe the current method I’ve implemented is simple, straightforward, and already working as expected. Should we keep it, as it ensures stability and ease of implementation?

2025-01-16 12:37 UTC, cathales commented on core/compressed_decoder.sv
>                end
It seems you added RVZCMT inside RVZCMP, is it what you meant?

```suggestion
              end else begin
                illegal_instr_o = 1'b1;
              end
            end else if (CVA6Cfg.RVZCMT && (instr_i[12:10] == 3'b000)) begin  //jt/jalt instruction
              is_zcmt_instr_o = 1'b1;
            end else begin
              illegal_instr_o = 1'b1;
            end
```

2025-01-16 12:38 UTC, farhan-108 commented on core/include/riscv_pkg.sv
> +  } jvt_t;
@cathales it is used in
https://github.com/openhwgroup/cva6/blob/bdcebe85e248c79cfdd5ad38f15934fac55a7f17/core/csr_regfile.sv#L301
https://github.com/openhwgroup/cva6/blob/bdcebe85e248c79cfdd5ad38f15934fac55a7f17/core/include/rvfi_types.svh#L134

2025-01-16 12:39 UTC, cathales commented on core/zcmt_decoder.sv
> +          jump_address_o = $unsigned($signed(req_port_i.data_rdata) - $signed(pc_i));
Both reducing area now or in a later PR are okay to me.
Maybe @JeanRochCoulon has opinion on this?

2025-01-16 12:46 UTC, farhan-108 commented on core/compressed_decoder.sv
>                end
@cathales 
The first condition will check if it is a ZCM* instruction (ZCMT || ZCMP). Within that, it further checks for ZCMT & (instr_i[12:10] == 3'b000).
https://github.com/openhwgroup/cva6/blob/bdcebe85e248c79cfdd5ad38f15934fac55a7f17/core/compressed_decoder.sv#L873-L881

2025-01-16 12:50 UTC, cathales commented on core/compressed_decoder.sv
>                end
So what if we have `RVZCMT && !RVZCMP` in the configuration and we get a Zcmp instruction? The `illegal_instr_o` won’t be raised, so it will be a bug, right?

I think it will be easier to maintain if we do not mix the two different options.

2025-01-16 14:14 UTC, farhan-108 commented on core/compressed_decoder.sv
>                end
@cathales 
Thank you so much for your feedback. I have separated out both conditions.

2025-01-16 14:15 UTC, cathales commented on core/compressed_decoder.sv
>                end
Thanks for the modifications, this looks really good now!

2025-01-16 14:16 UTC, farhan-108 commented on core/include/riscv_pkg.sv
> +  } jvt_t;
@cathales 
I have implemented the suggested changes as per your feedback. Thanks

2025-01-16 14:19 UTC, cathales commented on verif/sim/cva6.py
Was this new change intended?

2025-01-16 14:23 UTC, farhan-108 commented on verif/sim/cva6.py
typo mistake, sorry.

2025-01-16 14:25 UTC, cathales commented on verif/sim/cva6.py
No worries

2025-01-17 11:17 UTC, cathales commented on core/include/riscv_pkg.sv
> +  } jvt_t;
When I wrote "move the concatenation" I meant only move the `{ a, b }` expression.
Can you insert the following line in `core/cva6_rvfi.sv`, please?

```systemverilog
`CONNECT_RVFI_SAME(CVA6Cfg.RVZCMT, jvt)
```

It is the same as the one you wrote, but without the concatenation.

2025-01-17 13:24 UTC, farhan-108 commented on core/include/riscv_pkg.sv
> +  } jvt_t;
Done

2025-01-17 13:38 UTC, JeanRochCoulon commented
@farhan-108  can you rebase ?   (mandatory to merge)

2025-01-17 13:42 UTC, cathales commented on core/include/riscv_pkg.sv
> +  } jvt_t;
Thank you!

2025-01-17 13:42 UTC, cathales approved these changes

2025-01-17 13:43 UTC, cathales approved these changes

2025-01-17 13:44 UTC, farhan-108 commented
> @farhan-108 can you rebase ? (mandatory to merge)

@JeanRochCoulon Done

2025-01-17 14:19 UTC, cathales commented
Ah, the pipeline passed for 2b395d1 but not for the current version of the branch 964b2b8

2025-01-17 14:37 UTC, cathales commented
I have restarted the failed job and it passed. The remainder of the jobs (which were blocked by the failed job) are now running.

2025-01-20 16:55 UTC, JeanRochCoulon commented
Great Thales CI passes.
But all GitHub action CI tests do not pass for 64bits configuration, have you identify the root cause?

2025-01-20 17:12 UTC, cathales commented
Here is the error printed in GitHub CI.

Could it be an issue with HPDCache?

`Fri, 17 Jan 2025 13:49:29 ERROR    ERROR return code: True/2, cmd:make veri-testharness target=cv64a6_imafdc_sv39_hpdcache_wb variant=rv64gc_zba_zbb_zbs_zbc_zbkb elf=/home/runner/work/cva6/cva6/verif/sim/out_2025-01-17/directed_tests/add-01.o path_var=/home/runner/work/cva6/cva6/ tool_path=/home/runner/work/cva6/cva6/tools/spike/bin isscomp_opts="" issrun_opts="+tb_performance_mode+debug_disable=1+UVM_VERBOSITY=UVM_NONE +ntb_random_seed=1" isspostrun_opts="0x0000000080000000" log=/home/runner/work/cva6/cva6/verif/sim/out_2025-01-17/veri-testharness_sim/rv64i_m-add-01.cv64a6_imafdc_sv39_hpdcache_wb.log &> /home/runner/work/cva6/cva6/verif/sim/out_2025-01-17/veri-testharness_sim/rv64i_m-add-01.cv64a6_imafdc_sv39_hpdcache_wb.log.iss`

2025-01-27 08:01 UTC, cathales approved these changes

2025-01-27 08:41 UTC, cathales approved these changes

2025-01-27 09:10 UTC, ASintzoff commented
sorry to be a little bit picky, could you add license in the header of the new files?

```
// Licensed under the Solderpad Hardware Licence, Version 2.1 (the "License");
// you may not use this file except in compliance with the License.
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// You may obtain a copy of the License at https://solderpad.org/licenses/
```

2025-01-27 12:10 UTC, fatimasaleem commented
Hi @JeanRochCoulon hope you are doing well. Can you please give a final review and merge this? Thanks.

2025-01-27 12:23 UTC, merged

2025-01-27 12:24 UTC, JeanRochCoulon commented
@farhan-108 @fatimasaleem 
Great work and contribution !