remove global import
openhwgroup/cva6 pull request #489
Opened 2020-07-31 12:32 UTC by whutddk

## fix #482 
Global imports have been fixed in this PR.

pkg name in this PR may conflict with the pkg name in #485  , but don't worry, I will solve this no matter which PR is merged first.

2020-08-24 12:17 UTC, zarubaf commented
Thank you very much for bringing this up and providing a fix. Can we change the pull request to move the global imports to the module body i.e., `module ariane import ariane_pkg::*; #(`. That should greatly reduce the diff and make it easier to merge :-D

Thanks!

2020-08-25 08:56 UTC, whutddk commented
I have moved the global imports to the module body already. But the name `is_branch` in `frontend.sv line 139` is collided with `ariane_pkg::is_branch`. As a result, I renamed `ariane_pkg::is_branch` to `ariane_pkg::isBranch`.

By the way, should I clean up the package prefixes of the logic? I think it will be easier to fix #477 and complete #485 after that, because the diff 
will greatly reduce.

2020-08-26 09:04 UTC, zarubaf requested changes
Thanks for contributing your time! Let's remove the commented import statements and I propose another function name ;-) Then we are good to merge.
Regarding the package prefix. Can we do this on a step-by-step basis so that the diff gets maintainable? (In a different PR)

2020-08-26 09:04 UTC, zarubaf commented on include/ariane_pkg.sv
> +    function automatic logic isBranch (input fu_op op);
Can we rename the function name to `op_is_branch` (our style guide recommends function to be `snake_case`)?
```suggestion
    function automatic logic op_is_branch (input fu_op op);
```

2020-08-26 09:04 UTC, zarubaf commented on src/branch_unit.sv
> +            if (ariane_pkg::isBranch(fu_data_i.operator) && branch_comp_res_i != (branch_predict_i.cf == ariane_pkg::Branch)) begin
```suggestion
            if (ariane_pkg::op_is_branch(fu_data_i.operator) && branch_comp_res_i != (branch_predict_i.cf == ariane_pkg::Branch)) begin
```

2020-08-26 09:37 UTC, whutddk commented
Hi, I have resolved the issues in the review.

2020-08-26 10:22 UTC, zarubaf approved these changes
Terrific. LGTM

2020-08-26 10:40 UTC, merged