added c.jal instruction support for RV32C
openhwgroup/cva6 pull request #621
Opened 2021-02-22 09:30 UTC by sjthales

2021-02-22 09:43 UTC, zarubaf requested changes
Thanks for this contribution! A couple of nits from my side. Can you please make sure that your commits are covered by a valid ECA i.e., the ECA CI check passes?

2021-02-22 09:43 UTC, zarubaf commented on src/compressed_decoder.sv
> +			if (riscv::XLEN==64) begin
The indentation seems to be a bit off. I think we are using 4 space.

Also please but space around the operators to be consistent with the rest of the code.
```suggestion
			if (riscv::XLEN == 64) begin
```

2021-02-22 09:43 UTC, zarubaf commented on src/frontend/instr_scan.sv
> +    assign rvc_call_o   = rvc_jalr_o | ((instr_i[15:13] == riscv::OpcodeC1Jal) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1));
Seems a bit strange to compare a 2-bit signal with the 3 bit `riscv::OpcodeC1`. Shouldn't that also depend on how the core is configured?

2021-02-22 09:43 UTC, zarubaf commented on src/compressed_decoder.sv
> +                            if (instr_i[11:7] != 5'h0) // only valid if the destination is not r0
Please put `begin`/`end` according to our [coding style](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#begin--end).

2021-02-22 09:58 UTC, sjthales commented on src/frontend/instr_scan.sv
> +    assign rvc_call_o   = rvc_jalr_o | ((instr_i[15:13] == riscv::OpcodeC1Jal) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1));
`riscv::OpcodeC1` is a 2-bit local parameter and no it doesn't depend on the core configuration.
compressed instruction is defined with `opcode=intruction[1:0]` and `funct3=instruction[15:13]` in this case whatever the core configuration.

2021-02-22 10:14 UTC, zarubaf commented on src/frontend/instr_scan.sv
> +    assign rvc_call_o   = rvc_jalr_o | ((instr_i[15:13] == riscv::OpcodeC1Jal) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1));
But wouldn't the compressed `addiw` now trigger the `rvc_call_o` in the 64-bit case?

2021-02-22 10:29 UTC, sjthales commented on src/frontend/instr_scan.sv
> +    assign rvc_call_o   = rvc_jalr_o | ((instr_i[15:13] == riscv::OpcodeC1Jal) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1));
you are right, I will add a condition.

2021-02-23 09:52 UTC, zarubaf requested changes
Almost there.

2021-02-23 09:52 UTC, zarubaf commented on src/frontend/instr_scan.sv
> +    assign rvc_jump_o   = (riscv::XLEN == 64) ?
I would suggest you create a new signal. i.e., `rv32_rvc_jal`.
```systemverilog
assign rv32_rvc_jal = (riscv::XLEN == 32) & ((instr_i[15:13] == riscv::OpcodeC1Jal) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1));
```

2021-02-23 09:52 UTC, zarubaf commented on src/frontend/instr_scan.sv
> +    assign rvc_call_o   = (riscv::XLEN == 64) ? rvc_jalr_o : rvc_jalr_o | ((instr_i[15:13] == riscv::OpcodeC1Jal) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1));
```suggestion
    assign rvc_call_o   = rvc_jalr_o | rv32_rvc_jal;
```

2021-02-23 09:52 UTC, zarubaf commented on src/frontend/instr_scan.sv
> +
```suggestion
    assign rvc_jump_o   = ((instr_i[15:13] == riscv::OpcodeC1J) & is_rvc & (instr_i[1:0] == riscv::OpcodeC1)) | rv32_rvc_jal;

```

2021-02-23 09:52 UTC, zarubaf commented on src/compressed_decoder.sv
> +			if (riscv::XLEN == 64) begin
I think the indentation is still off. Also please make sure everything is formatted using spaces.

2021-02-23 09:52 UTC, zarubaf commented on src/compressed_decoder.sv
> +                            if (instr_i[11:7] != 5'h0) begin// only valid if the destination is not r0
```suggestion
                            if (instr_i[11:7] != 5'h0) begin // only valid if the destination is not r0
```

2021-02-23 10:45 UTC, zarubaf approved these changes
Thanks! Please make sure that you signed all your commits so that the ECA passes. Then we are good to merge.

2021-02-23 10:58 UTC, sjthales commented
Could you please tell me how to sign cause when I used `git commit -s` but it doesn't work.

2021-02-23 11:11 UTC, zarubaf commented
The problem that you have is that some of your authors are done from different email addresses (some are from github-noreply, I guess when you directly answered to an email, others are from your private email account).

The only way to fix this (without copying files etc., etc.) is to rebase your commits (a.k.a. re-write the commit history):

```
git rebase origin/master -x "git commit --amend --reset-author -s --no-edit"
```

As you've re-written your history you need to force push.

Also, be sure that your Github Author settings are correct as the rebase command will pick those things up from your global or local gitconfig.

2021-03-04 10:28 UTC, merged