added MMU Sv32 support for CV32A6
openhwgroup/cva6 pull request #622
Opened 2021-02-22 09:44 UTC by sjthales

2021-03-05 13:30 UTC, zarubaf requested changes
Thanks. Couple of nits.

2021-03-05 13:30 UTC, zarubaf commented on src/load_store_unit.sv
> +   /* mmu #(
Please remove this.

2021-03-05 13:30 UTC, zarubaf commented on src/load_store_unit.sv
> +    generate
`generate` block isn't needed.
```suggestion
    generate
```

2021-03-05 13:30 UTC, zarubaf commented on src/load_store_unit.sv
> +        if (MMU_PRESENT && (riscv::XLEN==64) ) begin : mmu_gen_sv39
Code-style require `gen_`
```suggestion
        if (MMU_PRESENT && (riscv::XLEN==64) ) begin : gen_mmu_sv39
```

2021-03-05 13:30 UTC, zarubaf commented on src/load_store_unit.sv
> +            mmu_sv32 #(
Please prefix with `cva6_`
```suggestion
            cva6_mmu_sv32 #(
```

2021-03-05 13:30 UTC, zarubaf commented on src/load_store_unit.sv
> +        end else begin : no_mmu_gen
```suggestion
        end else begin : gen_no_mmu
```

2021-03-05 13:30 UTC, zarubaf commented on src/mmu_sv32/mmu_sv32.sv
> +module mmu_sv32 import ariane_pkg::*; #(
Please prefix.
```suggestion
module cva6_mmu_sv32 import ariane_pkg::*; #(
```

2021-03-05 13:30 UTC, zarubaf commented on src/mmu_sv32/mmu_sv32.sv
> +    tlb_sv32 #(
```suggestion
    cva6_tlb_sv32 #(
```

2021-03-05 13:30 UTC, zarubaf commented on src/mmu_sv32/mmu_sv32.sv
> +    tlb_sv32 #(
```suggestion
    cva6_tlb_sv32 #(
```

2021-03-05 13:30 UTC, zarubaf commented on src/mmu_sv32/mmu_sv32.sv
> +    ptw_sv32  #(
```suggestion
    cva6_ptw_sv32  #(
```

2021-03-05 13:30 UTC, zarubaf commented on src/mmu_sv32/mmu_sv32.sv
> +	.vaddr_to_be_flushed_i ( vaddr_to_be_flushed_i  ),
Please correct the indentation.

2021-03-05 13:30 UTC, zarubaf commented on include/ariane_pkg.sv
> +        logic [27-1:0]         vpn;        //VPN (39bits) = 27bits + 12bits offset
```suggestion
        logic [27-1:0]         vpn;        // VPN (39bits) = 27bits + 12bits offset
```

2021-03-15 09:35 UTC, sjthales commented on src/load_store_unit.sv
> +            mmu_sv32 #(
Do you also want me to change mmu_sv32.sv into cva6_mmu_sv32.sv? And therefore  ptw_sv32.sv into cva6_ptw_sv32.sv and tlb_sv32.sv into  cva6_tlb_sv32.sv?
And mmu_sv32 directory into cva6_mmu_sv32 directory?

2021-03-15 12:00 UTC, zarubaf commented on src/load_store_unit.sv
> +            mmu_sv32 #(
https://github.com/openhwgroup/cva6/issues/477 
Essentially yes, but I don't think you need to re-name the folder ;-)

2021-03-15 12:09 UTC, sjthales commented on src/load_store_unit.sv
> +            mmu_sv32 #(
done

2021-03-18 14:48 UTC, zarubaf approved these changes

2021-03-18 14:48 UTC, zarubaf commented on src/load_store_unit.sv
> +    if (MMU_PRESENT && (riscv::XLEN==64) ) begin : gen_mmu_sv39
```suggestion
    if (MMU_PRESENT && (riscv::XLEN == 64)) begin : gen_mmu_sv39
```

2021-03-18 14:48 UTC, zarubaf commented on src/load_store_unit.sv
> +    end else if (MMU_PRESENT && (riscv::XLEN==32) ) begin : gen_mmu_sv32
```suggestion
    end else if (MMU_PRESENT && (riscv::XLEN == 32)) begin : gen_mmu_sv32
```

2021-03-30 07:31 UTC, zarubaf commented
Can you please re-base and add the PTW changes to your copy of the PTW (you see why I think duplication is not the right way to go ^^). Unfortunately you also need to close this pr and reopen. That will re-trigger Travis and we should be good to merge.

2021-06-17 07:29 UTC, closed without merging