Fix warning messages when using 32 bits version
openhwgroup/cva6 pull request #678
Opened 2021-06-07 12:30 UTC by E-Poulin

Signed-off-by: Emeric Poulin <emeric.poulin@thalesgroup.com>

2021-06-10 13:24 UTC, zarubaf requested changes

2021-06-10 13:24 UTC, zarubaf commented on src/csr_regfile.sv
> +    input  logic[riscv::VLEN-1:0] hart_id_i,                  // Hart id in a multicore environment (reflected in a CSR)
That should be `xlen` shouldn't it?

2021-06-11 07:37 UTC, E-Poulin commented on src/csr_regfile.sv
> +    input  logic[riscv::VLEN-1:0] hart_id_i,                  // Hart id in a multicore environment (reflected in a CSR)
Yes, you're right. I've checked the RISCV privileged manual and it's `xlen`. I'm gonna change it.

2021-06-11 08:54 UTC, zarubaf approved these changes
👍

2021-06-11 08:54 UTC, merged