Add CoreV-X-Interface, top hierarchy modification and rs3 for global purpose register file.
openhwgroup/cva6 pull request #780
Opened 2021-12-17 17:10 UTC by Gchauvon

Hello,

I propose a first implementation of the CoreV-X-Interface protocol for the cva6. You'll find the protocol here: [CoreV-X-Interface](https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/x_ext.html).

My implementation supports all mandatory interfaces from the protocol: 
- Issue interface
- Commit interface
- Result interface

Memory Interface and memory result interface used to connect coprocessor to CPU memory are not supported yet.
Compressed Interface may not be necessary as cva6 already support Compressed extension.

### CoreV-X-Interface Implementation
CoreV-X-IF is enabled via the `CVXIF_PRESENT` flag in `ariane_pkg.sv`. 
All illegal instructions are decoded under the R4-format. A new functional unit called `cvxif_fu.sv` is implemented in the `ex_stage.sv` and will proceed to create request on the X-Interface to offload illegal instructions. This module handle responses from the coprocessor aswell. 
In case an instruction is rejected ( illegal for CVA6 and coprocessor ), an `ILLEGAL_INSTR` exception is sent via the writeback bus. If the instruction is accepted, the coprocessor will give the result of the instruction so it can be writeback to the register file via the writeback bus aswell.

### Hierarchy modification
This PR contains a modification of the hierarchy for top modules. 
A new module called `cva6.sv` is basically `ariane.sv` with cvxif ports.
`ariane.sv` is now a wrapper containing `cva6.sv` and an example coprocessor when CVXIF is enable. `ariane.sv` keeps the same inputs/outputs as before so people that already have instantiated ariane can still use the repository.
Testharness now looks like this: 
![hierarchy](https://user-images.githubusercontent.com/94678394/146578667-ec1b5237-7adf-421d-aac1-d7f0af27a7b4.PNG)

### 3rd read ports for ariane_regfile
I also added the possibility to have a 3rd read port for the global purpose register ( `ariane_regfile` ). The CoreV-X-Interface protocol allows the CPU to transmit 3 sources registers to the coprocessor and it was my use case during development. I made it configurable via the `ariane_pkg::NR_RGPR_PORTS` because adding this 3rd port has an impact in area.

2021-12-17 17:20 UTC, JeanRochCoulon approved these changes

2021-12-20 11:41 UTC, zarubaf requested changes
Thanks this looks really good already. I've left a couple of nits and one block of logic I don't think is as you want it to behave IMHO :-) 

One additional thing I'd recommend is to check that the `NR_RGPR_PORTS` parameter has a sane value (i.e, max three and three only if CVX is enabled? you know it best). And check this with a proper `initial` assertion somewhere.

2021-12-20 11:41 UTC, zarubaf commented on core/cvxif_fu.sv
> +          cvxif_req_o.x_issue_req.rs[2]    = fu_data_i.imm;
```suggestion
          cvxif_req_o.x_issue_req.rs[2]    = fu_data_i.imm;
        end
```

2021-12-20 11:41 UTC, zarubaf commented on core/cvxif_fu.sv
> +      else begin
```suggestion
      end else begin
```

2021-12-20 11:41 UTC, zarubaf commented on core/decoder.sv
> +                if (~CVXIF_PRESENT) instruction_o.ex.valid = 1'b1;
```suggestion
                if (!CVXIF_PRESENT) instruction_o.ex.valid = 1'b1;
```

2021-12-20 11:41 UTC, zarubaf commented on core/ex_stage.sv
> +    generate
Same as above
```suggestion
```

2021-12-20 11:41 UTC, zarubaf commented on core/ex_stage.sv
> +        if (CVXIF_PRESENT) begin : cvxif_gen
```suggestion
        if (CVXIF_PRESENT) begin : gen_cvxif
```

2021-12-20 11:41 UTC, zarubaf commented on core/ex_stage.sv
> +        end else begin : no_cvxif_gen
```suggestion
        end else begin : gen_no_cvxif
```

2021-12-20 11:41 UTC, zarubaf commented on core/include/cvxif_pkg.sv
> +      x_compressed_req_t    x_compressed_req;
The indentation is somehow different than the other structs above.

2021-12-20 11:41 UTC, zarubaf commented on core/issue_read_operands.sv
> +    generate
```suggestion
```

2021-12-20 11:41 UTC, zarubaf commented on core/issue_read_operands.sv
> +              default:;
I think case items should be 4 spaces intended.
```suggestion
              CVXIF: begin
                  cvxif_valid_q       <= 1'b1;
                  cvxif_off_instr_q   <= orig_instr;
              end
              default:;
```

2021-12-20 11:41 UTC, zarubaf commented on core/issue_read_operands.sv
> +          if (!issue_instr_i.ex.valid && issue_instr_valid_i && issue_ack_o) begin
There is something wrong with the logic here. I'd suggest you split this in a proper comb and sequential block. 

I don't think that this is the logic you've intended, together with the reset this will give a strange priority.

2021-12-20 11:41 UTC, zarubaf commented on core/scoreboard.sv
> +  assign rs3_o = rs3[(ariane_pkg::NR_RGPR_PORTS == 3 ? riscv::XLEN : ariane_pkg::FLEN)-1:0];
I think this block would be more readable if written like this:
```suggestion
  if (ariane_pkg::NR_RGPR_PORTS == 3) begin : gen_gp_three_port
      assign rs3_o = rs3[riscv::XLEN-1:0];
  else begin : gen_fp_three_port
      assign rs3_o = rs3[ariane_pkg::FLEN-1:0];
  end
```

2021-12-20 11:41 UTC, zarubaf commented on corev_apu/cvxif_example/cvxif_example_coprocessor.sv
> +    .flush_i         ( 1'b0       ),
Indentation is off somehow

2021-12-20 11:41 UTC, zarubaf commented on corev_apu/cvxif_example/instr_decoder.sv
> +
```suggestion
```

2021-12-20 14:31 UTC, Gchauvon commented
I added 2 commits to be more align on style guideline. 
I also modified the block in `issue_read_operands.sv` which was indeed wrong. 
I added an initial assertion into `issue_read_operands.sv` to check the value for `NR_RGPR_PORTS` which is 2 when CVXIF is disable and can be either 2 or 3 when it is enable.

2021-12-22 11:30 UTC, zarubaf approved these changes
Thanks a lot! LGTM

2021-12-22 11:31 UTC, merged