Update repo user docs
openhwgroup/cva6 pull request #841
Opened 2022-03-22 01:35 UTC by MikeOpenHWGroup

This pull-request is made at the request of @rickoco to give the GitHub repos for CORE-V cores a more common "look and feel".

2022-03-22 02:26 UTC, DBees commented
Style guidelines refer to an inactive repo in PULP which refers out to LowRISC. Seems to be rather distant from OpenHW

2022-03-22 07:18 UTC, zarubaf approved these changes

2022-03-22 09:04 UTC, ASintzoff commented on CONTRIBUTING.md
> +See the [Git Cheats](https://github.com/openhwgroup/core-v-verif/blob/master/GitCheats.md) for a useful nominclature.
s/nominclature/nomenclature/

2022-03-22 11:24 UTC, JeanRochCoulon approved these changes

2022-03-22 13:12 UTC, MikeOpenHWGroup commented
Comment from @DBees 
> Style guidelines refer to an inactive repo in PULP which refers out to LowRISC. Seems to be rather distant from OpenHW

I believe you are referring to the current head of the master branch.  This pull-request replaces the reference to the inactive PULP repo with a direct reference to the lowRISC styleguide.  This guide was formally adopted by the CTG for RTL coding so it's the right one to point at.

2022-03-23 09:47 UTC, ASintzoff approved these changes

2022-03-23 10:17 UTC, davideschiavone requested changes

2022-03-23 10:17 UTC, davideschiavone commented on README.md
> +The directory structure separates the [CVA6 RISC-V CPU](#cva6-risc-v-cpu) core from the COREV-APU [FPGA Emulation](#corev-apu-fpga-emulation).
CORE-V

2022-03-23 17:52 UTC, DBees commented on README.md
> +The directory structure separates the [CVA6 RISC-V CPU](#cva6-risc-v-cpu) core from the COREV-APU [FPGA Emulation](#corev-apu-fpga-emulation).
@MikeOpenHWGroup sound good

2022-03-25 12:48 UTC, MikeOpenHWGroup commented on README.md
> +The directory structure separates the [CVA6 RISC-V CPU](#cva6-risc-v-cpu) core from the COREV-APU [FPGA Emulation](#corev-apu-fpga-emulation).
Good catch @davideschiavone.  Fixed.

2022-03-25 13:03 UTC, davideschiavone approved these changes

2022-04-06 08:09 UTC, merged