updated csr_regfile to support mandatory mcycle and minstret counter also added support to make perf_counters optional…
openhwgroup/cva6 pull request #843
Opened 2022-03-25 12:29 UTC by nathpranay

…as per specification for XLEN=32, also made perf_counters optional 
@zarubaf 

Signed-off-by: nathpranay <pranay.kantinath@thalesgroup.com>

2022-03-25 17:46 UTC, zarubaf requested changes

2022-03-25 17:46 UTC, zarubaf commented on core/cva6.sv
> + end
Remove new line

2022-03-25 17:46 UTC, zarubaf commented on core/cva6.sv
> + endgenerate
```suggestion
```

2022-03-25 17:46 UTC, zarubaf commented on core/csr_regfile.sv
> +                riscv::CSR_CYCLE:              csr_rdata = riscv::IS_XLEN32 ? cycle_q[31:0] : cycle_q;
What does the standard say about `CYCLE_H` In 64 bit mode? Should it throw an illegal instruction exception?

2022-03-28 08:49 UTC, Moschn commented on core/csr_regfile.sv
> +                riscv::CSR_MCYCLE:             cycle_d[31:0]  = csr_wdata;
I do not typically leave any comments, but I was just wondering what would happen on a 64bit configuration if the write value is larger than 32 bits. To my understanding, only the lower 32 bits would be overwritten, the upper bits would just remain. 

Most probably I am wrong though so feel free to ignore this comment.

2022-03-29 04:48 UTC, nathpranay commented on core/csr_regfile.sv
> +                riscv::CSR_CYCLE:              csr_rdata = riscv::IS_XLEN32 ? cycle_q[31:0] : cycle_q;
As per riscv-privileged-v1.10.pdf [ Chapter 2] : " Attempts to access a non-existent CSR raise an illegal instruction exception. Attempts to access a CSR without appropriate privilege level or to write a read-only register also raise illegal instruction exceptions. A read/write register might also contain some bits that are read-only, in which case
writes to the read-only bits are ignored." As per spec, all this _H CSR are RV32 only. In that way, in 64 Bit mode, it should throw illegal instruction.

2022-03-29 04:48 UTC, nathpranay commented on core/csr_regfile.sv
> +                riscv::CSR_MCYCLE:             cycle_d[31:0]  = csr_wdata;
Hi,
As per spec:
0xB00 MRW mcycle Machine cycle counter.
0xB02 MRW minstret Machine instructions-retired counter.
0xB03 MRW mhpmcounter3 Machine performance-monitoring counter.
0xB04 MRW mhpmcounter4 Machine performance-monitoring counter.
.
.
.
0xB1F MRW mhpmcounter31 Machine performance-monitoring counter.
0xB80 MRW mcycleh Upper 32 bits of mcycle, RV32I only.
0xB82 MRW minstreth Upper 32 bits of minstret, RV32I only.
0xB83 MRW mhpmcounter3h Upper 32 bits of mhpmcounter3, RV32I only.
0xB84 MRW mhpmcounter4h Upper 32 bits of mhpmcounter4, RV32I only.
.
.
.
0xB9F MRW mhpmcounter31h Upper 32 bits of mhpmcounter31, RV32I only

When XLEN=32, 0xB00(mcycle) and 0xB80 (mcycleh) together makes 64bit mcycle counter. Reading 64 bit mcycle counter will be done by reading 2 sepearate 32 bit (0xB00 and 0xB80). Writing also shall be done similarly.
For XLEN=32 or 64 or 128 the performance counters width is 64 bit.

2022-03-29 05:01 UTC, zarubaf commented on core/csr_regfile.sv
> +                riscv::CSR_CYCLE:              csr_rdata = riscv::IS_XLEN32 ? cycle_q[31:0] : cycle_q;
So I think we need to make sure we throw an illegal instruction when trying to access the 32 only regs. Right now they would read zero.

2022-03-29 08:00 UTC, Moschn commented on core/csr_regfile.sv
> +                riscv::CSR_MCYCLE:             cycle_d[31:0]  = csr_wdata;
I am not questioning the size of `mcycle`. I am just wondering why only the lower 32 bits are writable. I understand that for XLEN=32, one can write to the upper 32bits by writing to `mcycleh`. However, in XLEN=64 the `mcycleh` is not available.   
We should be able to write to all 64bits of the cycle register for both XLEN=32 and XLEN=64 right?

2022-03-29 16:17 UTC, nathpranay commented on core/csr_regfile.sv
> +                riscv::CSR_CYCLE:              csr_rdata = riscv::IS_XLEN32 ? cycle_q[31:0] : cycle_q;
Yes, i agree with you. For pmpcfg1 and pmpcfg3 access while XLEN=64, also should throw an illegal instruction?

0x3A0 MRW pmpcfg0 Physical memory protection configuration.
0x3A1 MRW pmpcfg1 Physical memory protection configuration, RV32 only.
0x3A2 MRW pmpcfg2 Physical memory protection configuration.
0x3A3 MRW pmpcfg3 Physical memory protection configuration, RV32 only

2022-04-08 14:26 UTC, Gchauvon commented on core/csr_regfile.sv
> +                riscv::CSR_MINSTRET:           instret[31:0]  = csr_wdata;
Shouldn't it be `instret_d` instead of `instret` ? 
Otherwise the register will not be updated because `instret_q` takes the value of `instret_d` which is not updated with `instret` after those lines.

```suggestion
                riscv::CSR_MINSTRET:           instret_d[31:0]  = csr_wdata; 
```

2022-04-08 14:26 UTC, Gchauvon commented on core/csr_regfile.sv
> +                riscv::CSR_MINSTRET_H:         instret[63:32] = riscv::IS_XLEN32 ? csr_wdata : '0 ;
Same reason as previous line
```suggestion
                riscv::CSR_MINSTRET_H:         instret_d[63:32] = riscv::IS_XLEN32 ? csr_wdata : '0 ;
```

2022-05-12 08:47 UTC, zarubaf commented
I think the same functionality has been merged as part of #847

2022-05-12 08:47 UTC, closed without merging