Adding Support for Zba, Zbb, Zbc and Zbs extensions to CVA6
openhwgroup/cva6 pull request #878
Opened 2022-05-16 12:40 UTC by M-Ijaz-10x

## Introduction
This PR is the continuation of [issue-451](https://github.com/openhwgroup/cva6/issues/451) and adds support for zba, zbb, zbc and zbs extensions under the wrapper of a compiler directive **BITMANIP**. These changes have been tested with self-written single instruction tests and using the compliance tests with the core-v-verif infrastructure.
## Implementation
Added the support for all the ratified bitmanip extensions as defined under this [bitmanip-spec](https://github.com/riscv/riscv-bitmanip/releases/download/1.0.0/bitmanip-1.0.0-38-g865e7a7.pdf)

- Zba extension (Address generation instructions)
- Zbb extension (Basic bit-manipulation instructions)
- Zbc extension (Carry-less multiplication instructions)
- Zbs extension (Single-bit instructions)
### Integration of bitmanip hardware with cva6
The major changes have been done in the decoder which includes adding the RISC-V Bitmanip opcodes, selecting the Functional Unit from Multiplier and ALU of the Ariane core and implementing design logic for Bitmanip instructions in ALU and Multiplier FUs.
## Verification
### Assembly Tests
The functionality of each implemented Bitmanip instruction has been verified by running individual assembly tests related to that particular instruction on the updated design.
### Core-v-verif environment
The OpenHW group’s core-v-verif verification environment has been modified to support the latest riscv-arch-test infrastructure (PR: [Added the support to run latest riscv-arch-tests in core-v-verif CVA6 infrastructure](https://github.com/openhwgroup/core-v-verif/pull/1254)) and used to run the compliance tests ([base tests](https://github.com/riscv-non-isa/riscv-arch-test/tree/main/riscv-test-suite) + [bitmanip tests](https://github.com/riscv-non-isa/riscv-arch-test/pull/228)) on the updated design. All the required bitmanip tests have successfully passed.

2022-05-23 06:59 UTC, zarubaf requested changes
That is really great, thanks for the pull request! Logic looks good to me in general.

The only comments I have are around we handle the inclusion, we usually use parameters for that and try to avoid `ifdefs` as much as possible. So I've added some comments on how I think we can make this work using only parameters :-) Please do let me know whether there is something unclear from the comments?

2022-05-23 06:59 UTC, zarubaf commented on Makefile
> +defines        ?= WT_DCACHE+RVFI_TRACE+BITMANIP
We are trying to not use tick defines for the inclusion of features (i.e., selecting rv32, rv64, A, M, etc. extensions). That is all done using parameters. I would suggest you add a `parameter` to the `ariane_pkg` called.

```
parameter bit BITMANIP = 1'b1;
```

2022-05-23 06:59 UTC, zarubaf commented on core/Flist.cv64a6_imafdc_sv39
> ++define+BITMANIP
Shouldn't be necessary with the parameter in the package.

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +`ifdef BITMANIP
```suggestion
if (BITMANIP) : gen_bitmanip
```

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +
That can be moved into the block further down, so only one `BITMANIP` `if` is needed.

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +`endif
```suggestion
end
```

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +    (
Code style nit:
```suggestion
    ) i_clz_64b (
```
Same for all other instantiations

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
>      always_comb begin
You can split the `result_o` into two case statements:

1. The general one
2. The added one fort bitmanip

1. is always in (no need for ifdefs), the second only if `BITMANIP` is set.

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +`ifndef BITMANIP
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +`else
```suggestion
if (ariane_pkg::BITMANIP) begin
```

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
>              ANDL:  result_o = fu_data_i.operand_a & fu_data_i.operand_b;
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/alu.sv
> +`endif
```suggestion
end
```

2022-05-23 06:59 UTC, zarubaf commented on core/decoder.sv
>                      end else begin
For the decoder:

Best to use the existing decoder (try not to duplicate decoding functionality) and use `if (ariane_pkg::BITMANIP)` to distinguish more decoding cases in the existing decoder.

Let me know if that isn't entirely clear.

2022-05-23 06:59 UTC, zarubaf commented on core/mult.sv
> +`else
I would say best to always assume that the operator are defined.
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/mult.sv
> +
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +`else
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +`ifdef BITMANIP
```suggestion
if (ariane_pkg::BITMANIP) begin : gen_bitmanip
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +    for (genvar i=0; i<64; i++) begin
Nit:
```suggestion
    for (genvar i = 0; i < 64; i++) begin : gen_operands_reverse
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +    always @* begin
Pls use SV:
```suggestion
    always_comb begin
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +    integer i;
```suggestion
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +        for (i=0; i<=64; i++) begin
```suggestion
        for (int i = 0; i <= 64; i++) begin
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +    for (genvar i=0; i<64; i++) begin
```suggestion
    for (genvar i = 0; i < 64; i++) begin : gen_clmulr_reverse
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +`ifndef BITMANIP
Let's proceed like in the ALU place with two `case` blocks in the same `always_comb` block.

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +`ifdef BITMANIP
```suggestion
if (ariane_pkg::BITMANIP) : gen_bitmanip
```

2022-05-23 06:59 UTC, zarubaf commented on core/multiplier.sv
> +`endif
```suggestion
end
```

2022-05-23 19:46 UTC, M-Ijaz-10x commented
Thank you @zarubaf  for the review.
I have made all the suggested changes. Please let me know if I am missing anything. Thanks :)

2022-05-24 07:51 UTC, zarubaf requested changes
Terrific, thanks soo much. Only minor code formatting things and then we are good to go!

2022-05-24 07:51 UTC, zarubaf commented on core/Flist.cv64a6_imafdc_sv39
> +
```suggestion
```

2022-05-24 07:51 UTC, zarubaf commented on core/alu.sv
> +end
nit; indentation is off

2022-05-24 07:51 UTC, zarubaf commented on core/decoder.sv
> +                        if (ariane_pkg::BITMANIP)
nit; two-lines need `begin`/`else`

2022-05-24 07:51 UTC, zarubaf commented on core/multiplier.sv
> +    if (ariane_pkg::BITMANIP) begin
nit: gen blocks need `gen_` labels
```suggestion
    if (ariane_pkg::BITMANIP) begin : gen_bitmanip
```

2022-05-24 09:43 UTC, JeanRochCoulon commented
That's a very great contribution !! Thank for that

As I am not in office in the coming days, I will available to check the PR from June1st to check max frequency, gate count, and functional regression in 32 and 64 bits. I let you know.

2022-05-24 10:05 UTC, M-Ijaz-10x commented
> That's a very great contribution !! Thank for that
> 
> As I am not in office in the coming days, I will available to check the PR from June1st to check max frequency, gate count, and functional regression in 32 and 64 bits. I let you know.

Sure. No Problem!

2022-05-24 12:18 UTC, zarubaf approved these changes
Everything on my end is green! I will trigger the CI and @JeanRochCoulon you can merge if the PPA is okay for you! Thanks again @M-Ijaz-10x, that is a great contribution!

2022-05-24 12:50 UTC, M-Ijaz-10x commented
> Everything on my end is green! I will trigger the CI and @JeanRochCoulon you can merge if the PPA is okay for you! Thanks again @M-Ijaz-10x, that is a great contribution!

AL

2022-05-24 12:55 UTC, M-Ijaz-10x commented
> Everything on my end is green! I will trigger the CI and @JeanRochCoulon you can merge if the PPA is okay for you! Thanks again @M-Ijaz-10x, that is a great contribution!

Happy to contribute. :) Looking forward to contribute more in the future developments.

2022-05-28 16:14 UTC, ZenithalHourlyRate commented on core/alu.sv
> +    end
Actually we could use only two or even one `lzc` to implement all these instructions.

First, `CTZ(a) = CLZ(reversed(a))`, and `operand_a_rev` could be reused here, thus reducing 4 modules to 2.
https://github.com/openhwgroup/cva6/blob/75807530f26ba9a0ca501e9d3a6575ec375ed7ab/core/alu.sv#L39
https://github.com/openhwgroup/cva6/blob/75807530f26ba9a0ca501e9d3a6575ec375ed7ab/core/alu.sv#L122

Merging `CLZW` and `CLZ` is tricky, I've managed to do that in [my implementation](https://github.com/OpenRigil/rocket-chip/blob/03aa2cdfb5e39b2229c5275db70e45d797db9e57/src/main/scala/rocket/ABLU.scala#L143-L144), but it is not easy to apply that here.

2022-05-28 16:14 UTC, ZenithalHourlyRate commented on core/alu.sv
> +          rorw = ({{32{1'b0}},fu_data_i.operand_a[31:0]} >> fu_data_i.operand_b[4:0]) | ({{32{1'b0}},fu_data_i.operand_a[31:0]} << (riscv::XLEN-32-fu_data_i.operand_b[4:0]));
Actually ROLW could be emulated by ROL by rotating `ROL({operand_a[31:0]:operand_a[31:0]})`.

2022-06-01 18:22 UTC, M-Ijaz-10x commented
While making the suggested changes on the PR, a bug was overlooked in the design related to exceptions (illegal instruction in the decoder) which was probably causing the tests to fail (CI checks timed-out). This is fixed in the latest commit on this PR. These changes are tested by running RISC-V Compliance tests and Bitmanip tests which came out to be clean now.
@zarubaf  Can you please review the new changes and trigger the CI again? Apologies for the inconvenience. Thank you.

2022-06-03 10:00 UTC, JeanRochCoulon commented
Hello, thanks again for this contribution. I would request some modifications to make VCS and synthesis work. 

By running the Continuous Integration, I get some errors:
- During synthesis of 32bits version, Error:  ../..//core/csr_regfile.sv:574: Array index out of bounds instret[63:32], valid bounds are [31:0]. (ELAB-298)
- During synthesis 32bits, Error:  ../..//core/alu.sv:179: Array index out of bounds fu_data_i[63:0], valid bounds are [31:0]. (ELAB-298)
- When simulating with VCS, gen_bitmanip name is used twice in multiplier.sv

In another hand, as we would be pleased to enable/disable the bitmanip support by CVA6, could you add a config variable, as done in core/include/cv32a6_XXX_config_pkg.sv to configure it?  The generation of the RTL dedicated to bitmanip should be conditioned by it (decode, alu,...).

Regards

2022-06-06 12:27 UTC, M-Ijaz-10x commented
> * During synthesis of 32bits version, Error:  ../..//core/csr_regfile.sv:574: Array index out of bounds instret[63:32], valid bounds are [31:0]. (ELAB-298)

Hello @JeanRochCoulon, the above error was due to the changes made in [PR-847](https://github.com/openhwgroup/cva6/pull/847). Above [commit](https://github.com/openhwgroup/cva6/pull/878/commits/568d547b29aa4ca449d94121c65bc6b4e5bf4910) proposed a workable solution for this error, but @spersvold will need to review the fix.

The remaining two errors have also been resolved in the latest commits.

> 
> In another hand, as we would be pleased to enable/disable the bitmanip support by CVA6, could you add a config variable, as done in core/include/cv32a6_XXX_config_pkg.sv to configure it? The generation of the RTL dedicated to bitmanip should be conditioned by it (decode, alu,...).

From the start, we are confining all the bitmanip RTL changes under the [bitmanip parameter](https://github.com/openhwgroup/cva6/blob/568d547b29aa4ca449d94121c65bc6b4e5bf4910/core/include/ariane_pkg.sv#L307) defined in ariane_pkg.sv as [suggested](https://github.com/openhwgroup/cva6/pull/878#discussion_r879075147) by @zarubaf

2022-06-06 13:04 UTC, ZenithalHourlyRate commented on core/alu.sv
> +                RORW, RORIW:  result_o = {{riscv::XLEN-32{rorw[31]}}, rorw};
https://github.com/openhwgroup/cva6/pull/878#discussion_r884151422

Ahh, it seems that you have not resolved it. It turned out that I knew another technique but forget to add it in last review

1. It is observed that `rol(x) = ror(reverse(w))`, you can use `ror(shift_op_a)` to get `rol(a)`, just as the current design uses `srl` to get `sll`
2. It is observed that `rorw(x[31:0]) = ror({x[31:0],x[31:0]})[31:0]`. If you still want to leave `RORW` and `ROR` as two separate datapaths, at least `RORW` and `ROLW` could be merged.

2022-06-06 14:39 UTC, spersvold approved these changes
The change looks good to me. However, I noticed that "instret" will not work as intended when in 32-bit mode if you wrap it  (because the incrementing logic in lines 333-349 is only dealing with the temporary variable "instret" which is xlen_t only, and then casting to instret_d after).

This should be fixed in a different commit though, so I approve this one.

2022-06-07 13:12 UTC, JeanRochCoulon commented
Hello,
I get another eror compiling with VCS:
Error-[IRIPS] Illegal range in part select core-v-verif/core-v-cores/cva6/core/alu.sv, 191
  The range of the part select is illegal: fu_data_i.operand_a[(riscv::XLEN - 33):0]
Have a nice day

2022-06-23 09:37 UTC, JeanRochCoulon commented
I synthetized in 32 bits version, please find the error reported by dc_shell Synsopsys tool:

Error:  ../..//core/alu.sv:287: Array index out of bounds fu_data_i[63:56], valid bounds are [31:0]. (ELAB-298)
*** Presto compilation terminated with 1 errors. ***
Information: Building the design 'alu'. (HDL-193)
Warning: Unable to resolve reference 'alu' in 'ex_stage_1'. (LINK-5)

Regards

2022-07-01 10:08 UTC, zchamski commented
Hi @fatimasaleem, in order to make the validation of CVA6 synthesis smoother, we are implementing synthesis error/warning message extraction in the Thales public CI dashboard (https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_cva6.html).

Since this is still work in progress, here are the summaries of synthesis error/warning logs produced by our prototype filter on your latest push (20a181a).  Please let @JeanRochCoulon, @yanicasa and myself (@zchamski) know if they are sufficient for you to work on your code.

Synthesis 32b (cv32a60x): 
[cva6-bitmanip-synth-errors-32b.g20a181a.txt](https://github.com/openhwgroup/cva6/files/9027952/cva6-bitmanip-synth-errors-32b.g20a181a.txt)

Synthesis 64b (cv64a6_imafdc_sv39): 
[cva6-bitmanip-synth-errors-64b.g20a181a.txt](https://github.com/openhwgroup/cva6/files/9027961/cva6-bitmanip-synth-errors-64b.g20a181a.txt)

As soon as the log extractor is stable (and incorporates the required usability adjustments if any) we will announce it in due way.

2022-07-03 01:13 UTC, fatimasaleem commented
Hi @zchamski 
I have made the required changes, can you please trigger the CI checks again? Thanks. cc @JeanRochCoulon

2022-07-03 03:26 UTC, fatimasaleem commented on core/alu.sv
> +                RORW, RORIW:  result_o = {{riscv::XLEN-32{rorw[31]}}, rorw};
Thank you @ZenithalHourlyRate for your review, really appreciate it. I will make this last change in a separate follow-up PR. For now, I am keeping it in my notes. :)

2022-07-04 09:03 UTC, zchamski commented
Hi @fatimasaleem, the synthesis in the CI looks good!  BTW, the Thales public CI is triggered automatically on every Github push to either cva6 or core-v-verif, and you can check the CI results as follows:

* Go to the Thales CI dashboard landing page at https://riscv-ci.pages.thales-invia.fr/dashboard/
* Select the CVA6 dashboard:
![dashboard_homepage](https://user-images.githubusercontent.com/107464696/177115180-524720c1-a8b5-4fa3-9ac6-163cde291bc9.png)
* Select the CI pipeline of interest and click on the PASS/FAIL status button:
![dashboard_cva6_pipelines](https://user-images.githubusercontent.com/107464696/177116418-818e15da-420f-4911-9d9f-ad45f539e19b.png)
* Select a job of interest (typically 'ASIS Synthesis cv32a60x' or 'ASIC Synthesis cv64a6_imafdc_sv39') and click on its PASS/FAIL button:
![dashboard_pipeline_jobs](https://user-images.githubusercontent.com/107464696/177118179-d46d0d7a-fd7a-4f4b-a70a-89ac0ffa9295.png)
* This will display the log summaries of the given job.  For synthesis, the summaries cover total area (in gate equivalents), area-by-category figures (gate equivs and percentage), area-by-package figures (again gate equivs and percentage), and finally, any error/warning messages.
![dashboard_synthesis_job_details_1of2](https://user-images.githubusercontent.com/107464696/177119643-6cbdef10-19a1-429e-8997-d10f5d9e97bc.png)
![dashboard_synthesis_job_details_2of2](https://user-images.githubusercontent.com/107464696/177119701-52b5e7c1-30ef-4b29-a417-3aaf0039b43c.png)

Please let the usual suspects (@zchamski, @yanicasa, @JeanRochCoulon) know about your experience of using the Thales CI dashboard.

And to answer an almost certain question: no, there are no direct links to the inside of the dashboard, you have to click your way through...

2022-07-04 09:42 UTC, fatimasaleem commented
Thank you @zchamski for the details. It really is very helpful. 

@JeanRochCoulon Since the synthesis and regression run look green, can we merge this? or is there anything else that needs to be done/fixed?

Thanks & Regards,

2022-07-06 13:40 UTC, JeanRochCoulon approved these changes

2022-07-06 14:45 UTC, JeanRochCoulon commented
In parallel, @ASintzoff will have a look to the arc-test suite PR. It would be nice to get it

2022-07-06 17:12 UTC, merged