Make AXI transactions modifiable
openhwgroup/cva6 pull request #948
Opened 2022-09-02 13:56 UTC by niwis

The `modifiable` bit of `ax.cache` indicates whether an AXI transaction can be changed downstream (e.g. split, merged, etc.). This is needed by several AXI IPs.

Based on https://github.com/pulp-platform/snitch/pull/96 and https://github.com/pulp-platform/snitch/pull/231.

2022-11-03 08:00 UTC, JeanRochCoulon commented on core/axi_adapter.sv
> +    axi_req_o.ar.cache  = axi_pkg::CACHE_MODIFIABLE;
Hello @niwis,
Previously the aw.cache and ar.cache were set to 4'b0000.
The PR propose to set them to axi_pkg::CACHE_MODIFIABLE which is equal to 4'b0010. Is it your though to modify the transaction functionality in CVA6, or do you suggest to set axi_pkg::CACHE_MODIFIABLE to zero ?

2022-11-04 17:09 UTC, JeanRochCoulon commented on core/axi_adapter.sv
> +    axi_req_o.ar.cache  = axi_pkg::CACHE_MODIFIABLE;
Hello Nils, your PR have been discussed with @ASintzoff and Ala. CVA6 does not support modifiable transaction, so it cannot transmit a wrong information to the peripherals. Can I ask you to set axi_pkg::CACHE_MODIFIABLE to 4'b0 ?
Cheers

2023-02-22 07:55 UTC, zarubaf commented
I haven't seen this before. @JeanRochCoulon are you sure about this requirement? This will make the CPU basically useless in any system that has proper AXI support. AXI transactions that are unmodifiable are not allowed to be split, merged etc.

Usually, peripherals are attached to a smaller interconnect (32-bit) which also means that the transaction needs to be modified to be able to be placed on the 32-bit from CVA6 (> 64-bit) refill interface.

I am not sure I get the concern with "wrong information to the peripherals". Can you please explain? I would strongly vote this change in, otherwise you are forcing all the users that have a proper AXI subsystem to maintain that change out-of-tree.

2023-03-07 14:27 UTC, zarubaf approved these changes
LGTM

2023-03-07 14:37 UTC, MikeOpenHWGroup requested changes
This is a great contribution @niwis.  It would be better if it included an update to the AXI chapter of the User Manual ([link](https://github.com/openhwgroup/cva6/blob/master/docs/01_cva6_user/AXI_Interface.rst)).

2023-03-07 16:56 UTC, JeanRochCoulon commented
Ok, that's ok on my side. 
How to proceed ?   Do you update this PR to make it mergeable or do you integrate this modification in another PR ?
In parallel, AXI chapter will be updated by @ASintzoff to add this information.

2023-03-07 17:18 UTC, niwis commented
I have rebased the branch and it should be mergeable now. In this case, I will not update the user manual here.

2023-03-07 22:38 UTC, JeanRochCoulon commented
Unfortunately vcs-uvm tests are failed causing a compilation error in the CI.. Do you have the possibility to run the vcs-uvm tests to reproduce the compilation error ?

2023-03-10 03:09 UTC, zarubaf commented
I think `vcs-uvm` failed for another reason, right @JeanRochCoulon? So can we continue to merge this?

2023-03-10 08:22 UTC, JeanRochCoulon commented
The CI fails for other reason, I have to investigate. I keep you in touch

2023-03-10 10:40 UTC, JeanRochCoulon commented
Understood the error !!!   The error should be fixed by rebasing.  @niwis can you rebase please ?

2023-03-10 10:42 UTC, niwis commented
Sure, done

2023-03-10 11:04 UTC, JeanRochCoulon commented
Hello @AEzzejjari, the AXI configuration is modified, and the AXI UVM reports this error:

UVM_ERROR @ 783.500 ns : uvmt_cva6_axi_assert.sv(124) reporter [ AXI4 protocol checks assertion ] Violation of AXI4_CVA6_ARCAHCE
"/home/jrcoulon/Projects/ovh/core-v-verif/cva6/sim//../../cva6/tb/uvmt/uvmt_cva6_axi_assert.sv", 123: uvmt_cva6_tb.cva6_dut_wrap.axi_assert.cva6_axi_assert.cva6_arcache: started at 786500ps failed at 786500ps
	Offending '(axi_assert.ar_cache == 0)' 

Do you think AXI agent need to be updated to support the new feature ?

2023-03-11 14:41 UTC, zarubaf commented
@JeanRochCoulon @MikeOpenHWGroup  Seems to me we are in a chicken and egg situation, what shall we change first?

2023-03-12 19:07 UTC, JeanRochCoulon commented
@AEzzejjari is modifying the AXI assertion, I hope to be able to merge AXI fix + this PR on Monday !

2023-03-13 09:33 UTC, AEzzejjari commented
I made the modification in the assertion, here is the link to the PR https://github.com/openhwgroup/core-v-verif/pull/1718.

2023-03-13 09:57 UTC, merged