First release identifier is v0.1.0
openhwgroup/cva6 pull request #994
Opened 2022-11-09 17:41 UTC by MikeOpenHWGroup

This PR is mostly a global search-and-replace of "step 1" to "v0.1.0".  I also took the liberty of adding a parameter table to the instantiation sub-section.  This will need to be expanded, so it is just a placeholder for now.

2022-11-09 21:19 UTC, JeanRochCoulon commented on docs/design_spec/source/cva6_system.rst
> +The CV32A6 cwv0.1.0 core is fully synthesizable. It has been designed mainly for ASIC designs, but FPGA synthesis is supported as well.
cwv0.1.0 => v0.1.0

2022-11-09 21:21 UTC, JeanRochCoulon commented
@MikeOpenHWGroup, just a small syntax error in the text. That's all right for me !

2022-11-09 21:22 UTC, JeanRochCoulon requested changes
syntax erorr to be fixed, otherwise, it is ok for me !

2022-11-09 21:45 UTC, MikeOpenHWGroup commented on docs/design_spec/source/cva6_system.rst
> +The CV32A6 cwv0.1.0 core is fully synthesizable. It has been designed mainly for ASIC designs, but FPGA synthesis is supported as well.
Oops!  :blush: Good catch.  Fixed.

2022-11-10 13:28 UTC, JeanRochCoulon approved these changes

2022-11-10 13:29 UTC, merged